import { clubById } from "./data";
import { flag, hasTrait, injure, milestone, note, rel, stat } from "./mutate";
import { npcMood, npcName, who } from "./npc";
import type { GameEvent, GameState } from "./types";

/* =========================================================================
 * BANCO NARRATIVO NUEVO · BLOQUE 1
 * Entrenador · vestuario · agente · prensa/afición · partidos clave
 * Todas las escenas son nuevas (texto y respuestas propias) y llevan
 * `family` para que el selector no repita la misma plantilla narrativa.
 * ========================================================================= */

const nick = (s: GameState) => s.player.nickname || s.player.name.split(" ")[0] || s.player.name;
const club = (s: GameState) => clubById(s.clubId).name;
const short = (s: GameState) => clubById(s.clubId).short;
const starter = (s: GameState) => s.flags["status"] === 1 || (s.flags["titular"] ?? 0) === 1;

function conflict(s: GameState, text: string) {
  if (!s.memory.conflicts.includes(text)) s.memory.conflicts.push(text);
}
function promise(s: GameState, text: string) {
  if (!s.memory.promises.includes(text)) s.memory.promises.push(text);
}

/* ------------------------------- ENTRENADOR ------------------------------ */
const COACH: GameEvent[] = [
  {
    id: "nb_c_promesa_rota",
    kicker: "Despacho",
    title: "La promesa que no cumplió",
    image: "office",
    category: "club",
    family: "coach_conflict",
    requires: (s) => s.age >= 17 && s.rel.coach <= 62,
    text: (s) => `Hace tres semanas ${who(s, "coach")} te dijo: "el próximo lo empiezas tú". Has visto los tres siguientes desde el banquillo. Hoy te lo cruzas solo en el pasillo del gimnasio y él aparta la mirada primero.`,
    choices: [
      { id: "recordar", label: "\"Míster, ¿se acuerda de lo que me dijo?\"", hint: "Directo, sin gritar", outcome: "Se para. Tarda en responder. \"Sí. Y no te lo he dado. Tienes razón.\"", apply: (s) => { rel(s, "coach", 4); stat(s, "morale", 5); flag(s, "encaro_mister"); } },
      { id: "tragar", label: "Saludar y seguir", outcome: "Te tragas el sapo. En el gimnasio levantas más peso del que tocaba.", apply: (s) => { stat(s, "morale", -6); stat(s, "fitness", 4); rel(s, "coach", 1); } },
      { id: "portazo", label: "Soltarle que estás harto", hint: "Puede costarte caro", outcome: "Levanta la voz más que tú. El pasillo entero lo oye.", apply: (s) => { rel(s, "coach", -12); stat(s, "fame", 2); conflict(s, "Discutiste a gritos con el entrenador"); flag(s, "bronca_mister"); } },
    ],
  },
  {
    id: "nb_c_cambio_posicion",
    kicker: "Pizarra",
    title: "Te quiere en otro sitio",
    image: "office",
    category: "training",
    family: "coach_tactics",
    requires: (s) => s.age >= 17 && !s.flags["cambio_pos"],
    text: (s) => `${who(s, "coach")} dibuja una flecha que va de tu posición habitual a otra distinta. "Quince metros más atrás. Vas a tocar más balones y vas a sufrir más. Tú decides si lo pruebas."`,
    choices: [
      { id: "probar", label: "Probarlo sin rechistar", outcome: "Los primeros días es un caos. Al décimo, entiendes el juego mejor que nunca.", apply: (s) => { stat(s, "overall", 3); rel(s, "coach", 8); flag(s, "cambio_pos"); note(s, "Empiezas a jugar en una posición nueva.", "neutral"); } },
      { id: "condicion", label: "Aceptar, pero pidiendo minutos a cambio", outcome: "\"Me gusta que negocies. Vale.\"", apply: (s) => { rel(s, "coach", 3); stat(s, "morale", 5); flag(s, "cambio_pos"); promise(s, "El míster te prometió minutos por cambiar de posición"); } },
      { id: "negarse", label: "\"Yo soy de mi puesto, míster\"", outcome: "Borra la flecha con la manga. No vuelve a mencionarlo.", apply: (s) => { rel(s, "coach", -7); stat(s, "morale", 2); conflict(s, "Rechazaste cambiar de posición"); } },
    ],
  },
  {
    id: "nb_c_ultimatum",
    kicker: "Ultimátum",
    title: "Tres partidos",
    image: "locker",
    category: "club",
    family: "coach_conflict",
    requires: (s) => s.age >= 18 && s.form < 48,
    text: (s) => `${who(s, "coach")} te sienta en el banco vacío del vestuario cuando ya no queda nadie. "Tienes tres partidos. Si en tres partidos sigues jugando con miedo, busco otra solución. No es una amenaza, es un calendario."`,
    choices: [
      { id: "aceptar", label: "\"Tres me sobran\"", outcome: "Sonríe de lado. \"Ojalá.\"", apply: (s) => { stat(s, "form", 7); stat(s, "morale", 6); rel(s, "coach", 4); promise(s, "Prometiste responder en tres partidos"); } },
      { id: "honesto", label: "Reconocer que estás bloqueado", hint: "Vulnerable", outcome: "Se queda callado un rato. \"Eso no me lo dice casi nadie. Mañana hablamos con el psicólogo del club.\"", apply: (s) => { rel(s, "coach", 9); stat(s, "morale", 9); stat(s, "form", 3); } },
      { id: "ofendido", label: "\"Con tres partidos no se juzga a nadie\"", outcome: "\"Aquí se juzga con menos. Bienvenido.\"", apply: (s) => { rel(s, "coach", -6); stat(s, "form", 2); stat(s, "morale", -3); } },
    ],
  },
  {
    id: "nb_c_favoritismo",
    kicker: "Vestuario",
    title: "El intocable",
    image: "training",
    category: "club",
    family: "coach_fair",
    requires: (s) => s.age >= 17,
    text: (s) => `Hay un jugador que falla, pierde balones y sale en el once igual. Medio vestuario murmura que ${npcName(s, "coach")} lo protege por algo que nadie dice en voz alta. Hoy en el rondo el murmullo se ha oído demasiado.`,
    choices: [
      { id: "callar", label: "No entrar en el corrillo", outcome: "Te vas al gimnasio. El corrillo sigue sin ti.", apply: (s) => { stat(s, "discipline", 6); rel(s, "coach", 3); rel(s, "dressing", -2); } },
      { id: "sumarse", label: "Sumarte a la queja", outcome: "El grupo te siente de los suyos. Alguien lo repetirá donde no debe.", apply: (s) => { rel(s, "dressing", 8); rel(s, "coach", -5); flag(s, "corrillo"); } },
      { id: "preguntar", label: "Preguntarle al míster a la cara por qué", hint: "Valiente o suicida", outcome: "\"Porque yo pongo el once. Cuando lo pongas tú, lo cambias.\" Pero se le queda el gesto torcido.", apply: (s) => { rel(s, "coach", -4); rel(s, "dressing", 6); stat(s, "fame", 1); flag(s, "encaro_mister"); } },
    ],
  },
  {
    id: "nb_c_sin_explicacion",
    kicker: "Convocatoria",
    title: "Fuera de la lista, sin motivo",
    image: "locker",
    category: "club",
    family: "coach_conflict",
    requires: (s) => s.age >= 17 && s.stage !== "youth",
    text: (s) => `Lista en el corcho. No estás. No hay lesión, no hay sanción, no hay explicación. ${npcName(s, "coach")} sale del vestuario mirando el móvil como si el corcho no existiera.`,
    choices: [
      { id: "esperar", label: "Esperarle en el aparcamiento", outcome: "Media hora de pie. Al final aparece: \"decisión técnica\". Nada más.", apply: (s) => { stat(s, "morale", -5); rel(s, "coach", 2); } },
      { id: "entrenar", label: "Irte a entrenar por tu cuenta el sábado", outcome: "El preparador físico te ve solo bajo la lluvia y se lo cuenta a alguien.", apply: (s) => { stat(s, "fitness", 7); stat(s, "form", 4); rel(s, "coach", 5); } },
      { id: "agente", label: "Llamar a tu agente y montarla", outcome: "Tu agente hace tres llamadas. En el club no gusta.", apply: (s) => { rel(s, "agent", 6); rel(s, "coach", -8); flag(s, "presion_agente"); conflict(s, "Usaste a tu agente contra el entrenador"); } },
    ],
  },
  {
    id: "nb_c_confianza_publica",
    kicker: "Sala de prensa",
    title: "Te defiende en público",
    image: "press",
    category: "club",
    family: "coach_support",
    requires: (s) => s.rel.coach >= 62 && s.age >= 17,
    text: (s) => `Un periodista pregunta por qué sigues jugando si llevas cuatro partidos sin aparecer. ${who(s, "coach")} responde: "Porque veo lo que hace cuando no tiene el balón. Y porque me da la gana."`,
    choices: [
      { id: "gracias", label: "Agradecérselo en privado", outcome: "\"No me des las gracias. Devuélvemelo el domingo.\"", apply: (s) => { rel(s, "coach", 6); stat(s, "morale", 8); promise(s, "Le debes un partido al entrenador"); } },
      { id: "publico", label: "Devolvérselo públicamente en redes", outcome: "Queda bien fuera, algo pelota dentro.", apply: (s) => { stat(s, "fame", 5); rel(s, "coach", 2); rel(s, "dressing", -3); } },
    ],
  },
  {
    id: "nb_c_charla_privada",
    kicker: "Coche",
    title: "Te lleva a casa",
    image: "travel",
    category: "life",
    family: "coach_support",
    requires: (s) => s.age <= 21 && s.rel.coach >= 55,
    text: (s) => `Se ha ido el último autobús y ${who(s, "coach")} te ofrece llevarte. Veinte minutos de coche en los que no habla de fútbol ni una vez: habla de su hijo, del tráfico y de un disco viejo que suena bajito.`,
    choices: [
      { id: "escuchar", label: "Escuchar y no hablar de fútbol tú tampoco", outcome: "Al bajarte dice: \"mañana volvemos a ser míster y jugador\". Pero ya no del todo.", apply: (s) => { rel(s, "coach", 9); stat(s, "morale", 6); } },
      { id: "aprovechar", label: "Aprovechar para preguntar por tu sitio", outcome: "Cambia el tono. \"Aquí no. Mañana en el despacho.\" Y mañana no hay despacho.", apply: (s) => { rel(s, "coach", -4); stat(s, "morale", -2); } },
    ],
  },
  {
    id: "nb_c_bronca_descanso",
    kicker: "Descanso",
    title: "Bronca en el descanso",
    image: "locker",
    category: "club",
    family: "coach_conflict",
    requires: (s) => s.age >= 17 && s.form < 60,
    text: (s) => `0-2 al descanso. ${npcName(s, "coach")}, tu entrenador, tira la pizarra al suelo y dice tu nombre el primero. Once pares de ojos se giran hacia ti.`,
    choices: [
      { id: "asumir", label: "Bajar la cabeza y asumirlo", outcome: "Sales en la segunda parte y corres como un poseso.", apply: (s) => { stat(s, "form", 6); rel(s, "coach", 5); stat(s, "morale", -2); } },
      { id: "responder", label: "Responderle delante de todos", outcome: "El vestuario se congela. Un veterano te agarra del brazo.", apply: (s) => { rel(s, "coach", -11); rel(s, "dressing", 4); conflict(s, "Le contestaste al míster en el descanso"); flag(s, "bronca_mister"); } },
      { id: "senalar", label: "Señalar al que ha fallado de verdad", outcome: "Nadie te lo perdona, ni el míster.", apply: (s) => { rel(s, "dressing", -12); rel(s, "coach", -3); flag(s, "senalo_companero"); conflict(s, "Señalaste a un compañero en el vestuario"); } },
    ],
  },
];

/* -------------------------------- VESTUARIO ------------------------------ */
const DRESSING: GameEvent[] = [
  {
    id: "nb_v_novatada",
    kicker: "Vestuario",
    title: "Te toca cantar",
    image: "locker",
    category: "life",
    family: "rookie_hazing",
    requires: (s) => s.age <= 19 && !s.flags["novatada"],
    text: (s) => `Silla en medio del comedor. ${who(s, "captain")} golpea la mesa: "Novato, de pie". Treinta tíos esperando y tú sin saberte una canción entera.`,
    choices: [
      { id: "cantar", label: "Cantar fatal pero hasta el final", outcome: "Aplausos, gritos y un mote que te va a durar años.", apply: (s) => { rel(s, "dressing", 12); stat(s, "morale", 6); flag(s, "novatada"); npcMood(s, "captain", 8); } },
      { id: "bailar", label: "Cambiar la canción por un baile absurdo", outcome: "El vídeo llega a redes en once minutos.", apply: (s) => { rel(s, "dressing", 9); stat(s, "fame", 6); flag(s, "novatada"); } },
      { id: "negarse", label: "Negarte", outcome: "Se hace un silencio muy largo. Alguien dice \"vale, vale\" con retintín.", apply: (s) => { rel(s, "dressing", -10); stat(s, "discipline", 3); flag(s, "novatada"); conflict(s, "Te negaste a la novatada"); } },
    ],
  },
  {
    id: "nb_v_capitan_protege",
    kicker: "Vestuario",
    title: "El capitán da la cara",
    image: "locker",
    category: "life",
    family: "captain_bond",
    requires: (s) => s.age <= 22 && s.rel.dressing >= 45,
    text: (s) => `Un veterano te ha estado buscando las cosquillas toda la semana. Hoy, en la comida, ${who(s, "captain")} le corta en seco: "Al chaval lo dejas en paz. Si tienes algo, lo tienes conmigo".`,
    choices: [
      { id: "agradecer", label: "Agradecérselo después, a solas", outcome: "\"Aquí nos protegemos. Cuando llegue otro chaval, hazlo tú.\"", apply: (s) => { rel(s, "dressing", 8); npcMood(s, "captain", 10); flag(s, "deuda_capitan"); promise(s, "Le debes una al capitán"); } },
      { id: "solo", label: "Decirle que puedes solo", outcome: "Se encoge de hombros. \"Como quieras.\" Y la próxima vez no interviene.", apply: (s) => { npcMood(s, "captain", -8); stat(s, "morale", 3); } },
    ],
  },
  {
    id: "nb_v_celoso",
    kicker: "Vestuario",
    title: "El compañero que ya no te habla",
    image: "locker",
    category: "life",
    family: "teammate_envy",
    requires: (s) => s.age >= 17 && s.fame >= 18,
    text: (s) => `Desde que salió tu entrevista, ${who(s, "friend")} responde con monosílabos. Hoy te ha cambiado la taquilla de sitio "porque necesitaba espacio".`,
    choices: [
      { id: "hablar", label: "Preguntarle qué le pasa, directo", outcome: "\"Que llevas dos meses aquí y ya te tratan mejor que a mí.\" Al menos está dicho.", apply: (s) => { rel(s, "dressing", 5); npcMood(s, "friend", 6); stat(s, "morale", 3); } },
      { id: "invitar", label: "Invitarle a cenar y no hablar del tema", outcome: "A los postres se ríe por primera vez en semanas.", apply: (s) => { rel(s, "dressing", 9); npcMood(s, "friend", 12); } },
      { id: "pasar", label: "Pasar del tema", outcome: "El hielo se queda ahí, ocupando sitio.", apply: (s) => { npcMood(s, "friend", -6); rel(s, "dressing", -4); conflict(s, "Dejaste enfriar la amistad con un compañero"); } },
    ],
  },
  {
    id: "nb_v_grupo_whatsapp",
    kicker: "Móvil",
    title: "El grupo de WhatsApp",
    image: "locker",
    category: "life",
    family: "team_chat",
    requires: (s) => s.age >= 17,
    text: () => `247 mensajes sin leer. Alguien ha subido una captura del entrenador quejándose del horario y el grupo está encendido. Sales de la ducha y hay tres personas escribiendo a la vez.`,
    choices: [
      { id: "calmar", label: "Escribir \"borrad eso ya\"", outcome: "Se borra. Dos te lo agradecen en privado.", apply: (s) => { stat(s, "discipline", 6); rel(s, "dressing", 4); rel(s, "coach", 3); } },
      { id: "leña", label: "Echar leña con un meme", outcome: "Ochenta risas. Y una captura que sale del grupo.", apply: (s) => { rel(s, "dressing", 8); flag(s, "captura_fuera"); stat(s, "fame", 2); } },
      { id: "silenciar", label: "Silenciar el grupo y dormir", outcome: "Al día siguiente eres el único que no sabe nada. Curiosamente, el único limpio.", apply: (s) => { stat(s, "fitness", 4); rel(s, "dressing", -3); } },
    ],
  },
  {
    id: "nb_v_cena_equipo",
    kicker: "Cena de equipo",
    title: "La cena que se alarga",
    image: "celebration",
    category: "life",
    family: "team_dinner",
    requires: (s) => s.age >= 18,
    text: () => `Reservado al fondo, sobremesa larga y alguien propone alargar la noche. Mañana hay entreno a las diez. Cuatro se levantan para irse; seis piden otra ronda.`,
    choices: [
      { id: "irse", label: "Irte con los cuatro", outcome: "Duermes ocho horas. Al día siguiente eres el único que corre bien.", apply: (s) => { stat(s, "fitness", 6); stat(s, "discipline", 5); rel(s, "dressing", -2); } },
      { id: "quedarse", label: "Quedarte hasta el final", outcome: "Grupo, risas y una resaca que el preparador físico detecta a los diez minutos.", apply: (s) => { rel(s, "dressing", 10); stat(s, "fitness", -8); rel(s, "coach", -4); } },
      { id: "pagar", label: "Pagar la cuenta entera y marcharte", hint: "Cuesta dinero, compra respeto", outcome: "\"Este chaval es de los nuestros.\" El camarero también lo agradece.", apply: (s) => { rel(s, "dressing", 12); s.wealth = Math.max(0, (s.wealth ?? 0) - 1); stat(s, "fitness", 3); } },
    ],
  },
  {
    id: "nb_v_rival_puesto",
    kicker: "Competencia",
    title: "El que juega en tu puesto se lesiona",
    image: "injury",
    category: "life",
    family: "positional_rival",
    requires: (s) => s.age >= 17 && !starter(s),
    text: (s) => `${who(s, "rival")} se queda en el suelo agarrándose el gemelo. Todo el mundo mira al suelo; tú miras al banquillo. Y te odias un poco por eso.`,
    choices: [
      { id: "ayudar", label: "Ser el primero en llegar a ayudarle", outcome: "Se acuerda de esto mucho después, cuando le toca hablar bien de ti.", apply: (s) => { npcMood(s, "rival", 15); rel(s, "dressing", 8); stat(s, "morale", 4); flag(s, "ayude_rival"); } },
      { id: "preparar", label: "Ir directo a calentar", outcome: "Frío, útil y muy visible. El míster toma nota de las dos cosas.", apply: (s) => { rel(s, "coach", 5); stat(s, "form", 5); npcMood(s, "rival", -10); rel(s, "dressing", -4); } },
      { id: "mensaje", label: "Escribirle esa noche", outcome: "Te responde a las tres de la mañana: \"aprovéchalo, cabrón\".", apply: (s) => { npcMood(s, "rival", 10); stat(s, "morale", 5); } },
    ],
  },
  {
    id: "nb_v_peticion_ayuda",
    kicker: "Vestuario",
    title: "Un compañero te pide ayuda",
    image: "locker",
    category: "life",
    family: "teammate_help",
    requires: (s) => s.age >= 18 && s.rel.dressing >= 42,
    text: (s) => `${who(s, "friend")} te espera en el aparcamiento. Habla bajo: lleva dos meses sin cobrar la parte variable y en casa la cosa está fea. No pide dinero. Pide que le acompañes a hablar con el club.`,
    choices: [
      { id: "acompanar", label: "Acompañarle al despacho", outcome: "No se soluciona ese día, pero él no vuelve a estar solo en esto.", apply: (s) => { rel(s, "dressing", 12); npcMood(s, "friend", 14); rel(s, "coach", -2); flag(s, "apoye_companero"); } },
      { id: "dinero", label: "Ofrecerle dinero tuyo", outcome: "Se le rompe algo en la cara. Lo acepta y no lo olvida.", apply: (s) => { s.wealth = Math.max(0, (s.wealth ?? 0) - 2); npcMood(s, "friend", 18); rel(s, "dressing", 8); flag(s, "apoye_companero"); } },
      { id: "evitar", label: "Decirle que tú no te metes en eso", outcome: "Asiente demasiado rápido. Ya no te cuenta nada más.", apply: (s) => { npcMood(s, "friend", -14); rel(s, "dressing", -7); conflict(s, "Dejaste tirado a un compañero"); } },
    ],
  },
  {
    id: "nb_v_discusion_entreno",
    kicker: "Entrenamiento",
    title: "Manos al cuello en un rondo",
    image: "training",
    category: "training",
    family: "training_fight",
    requires: (s) => s.age >= 17,
    text: () => `Entrada tarde en un rondo tonto, un empujón, y de repente dos camisetas agarradas. El grupo tarda cuatro segundos en separar y treinta en decidir de quién es la culpa.`,
    choices: [
      { id: "disculpa", label: "Pedir perdón el primero", outcome: "Se corta la sangre. El míster aplaude con sorna, pero aplaude.", apply: (s) => { rel(s, "dressing", 6); rel(s, "coach", 6); stat(s, "discipline", 4); } },
      { id: "sostener", label: "Sostener la mirada sin bajar los brazos", outcome: "Nadie vuelve a entrarte fuerte en un rondo en meses.", apply: (s) => { rel(s, "dressing", 3); stat(s, "morale", 5); rel(s, "coach", -3); flag(s, "duro_vestuario"); } },
      { id: "humillar", label: "Reírte de él delante de todos", outcome: "Se ríen diez. Él no. Y tiene memoria.", apply: (s) => { rel(s, "dressing", -6); npcMood(s, "rival", -18); flag(s, "humille_companero"); conflict(s, "Humillaste a un compañero en el entrenamiento"); } },
    ],
  },
  {
    id: "nb_v_devolucion",
    kicker: "Vestuario",
    title: "Te la devuelven",
    image: "locker",
    category: "life",
    family: "callback",
    requires: (s) => (s.flags["humille_companero"] ?? 0) === 1 || (s.flags["senalo_companero"] ?? 0) === 1,
    text: (s) => `Rueda de prensa de un compañero. Le preguntan por el vestuario y responde mirando a cámara: "Hay gente que se ríe mucho de los demás y luego pide comprensión". No hace falta que diga tu nombre. ${nick(s)} lo entiende igual.`,
    choices: [
      { id: "asumir", label: "Reconocerlo y pedirle perdón de verdad", outcome: "Cuesta más que un partido entero. Funciona a medias.", apply: (s) => { rel(s, "dressing", 8); s.flags["humille_companero"] = 0; s.flags["senalo_companero"] = 0; stat(s, "morale", -3); } },
      { id: "guerra", label: "Contestarle públicamente", outcome: "Dos días de tertulias. Cero minutos ganados.", apply: (s) => { rel(s, "dressing", -8); stat(s, "fame", 6); rel(s, "coach", -5); } },
      { id: "silencio", label: "No entrar", outcome: "El tema muere solo, pero el vestuario ya ha elegido bando.", apply: (s) => { rel(s, "dressing", -3); stat(s, "discipline", 4); } },
    ],
  },
  {
    id: "nb_v_capitan_paga",
    kicker: "Callback",
    title: "El capitán te devuelve el favor",
    image: "press",
    category: "press",
    family: "callback",
    requires: (s) => (s.flags["deuda_capitan"] ?? 0) === 1 && s.form < 55,
    text: (s) => `Llevas semanas malas y la grada empieza a señalarte. ${who(s, "captain")} coge el micro sin que nadie se lo pida: "El que silbe a un chaval de la casa, que se quede en su casa".`,
    choices: [
      { id: "responder", label: "Responder en el campo", outcome: "El domingo dejas el alma. No siempre basta, pero esta vez casi.", apply: (s) => { stat(s, "form", 9); rel(s, "fans", 6); npcMood(s, "captain", 6); } },
      { id: "abrazo", label: "Abrazarle en el túnel sin decir nada", outcome: "Él lo entiende todo.", apply: (s) => { stat(s, "morale", 10); rel(s, "dressing", 7); } },
    ],
  },
];

/* --------------------------------- AGENTE -------------------------------- */
const AGENT: GameEvent[] = [
  {
    id: "nb_a_llamada_madrugada",
    kicker: "03:40",
    title: "Llamada a las cuatro de la mañana",
    image: "agent",
    category: "agent",
    family: "agent_call",
    requires: (s) => !!s.agent?.present && s.age >= 17,
    text: (s) => `El móvil vibra hasta caerse de la mesilla. Es ${s.agent.name}, tu representante. "No cuelgues. Tengo veinte minutos para decir un sí o un no y necesito saber si me dejas hablar por ti."`,
    choices: [
      { id: "adelante", label: "\"Habla.\"", hint: "Cheque en blanco", outcome: "No te cuenta con quién. A la semana entiendes que era serio.", apply: (s) => { rel(s, "agent", 10); flag(s, "cheque_blanco"); stat(s, "morale", 4); } },
      { id: "manana", label: "\"Mañana, con café y con nombres.\"", outcome: "Resopla. Al día siguiente aparece con dos carpetas.", apply: (s) => { rel(s, "agent", -3); stat(s, "discipline", 5); flag(s, "exijo_detalles"); } },
      { id: "colgar", label: "Colgar y volver a dormir", outcome: "Duermes ocho horas. Alguien firma en tu lugar.", apply: (s) => { rel(s, "agent", -9); stat(s, "fitness", 5); } },
    ],
  },
  {
    id: "nb_a_oferta_dudosa",
    kicker: "Agente",
    title: "Un club que no aparece en el mapa",
    image: "agent",
    category: "agent",
    family: "agent_offer",
    requires: (s) => !!s.agent?.present && s.age >= 18,
    text: (s) => `${s.agent.name}, tu representante, desliza el móvil por la mesa. Cifra grande, liga rara, club que se fundó hace catorce meses. "Es dinero real. El proyecto ya no sé."`,
    choices: [
      { id: "no", label: "\"Ni loco. Quiero jugar donde se vea.\"", outcome: "Aparta el móvil. \"Ojalá todos mis chavales dijeran eso.\"", apply: (s) => { rel(s, "agent", 4); stat(s, "morale", 5); s.memory.rejectedClubs.push("un proyecto exótico"); } },
      { id: "info", label: "Pedir que investigue quién paga", outcome: "Tres días después no vuelve a mencionarlo. Eso ya es una respuesta.", apply: (s) => { rel(s, "agent", 2); stat(s, "discipline", 5); flag(s, "exijo_detalles"); } },
      { id: "tentado", label: "Dejar la puerta abierta por el dinero", outcome: "Se te queda dentro la cifra. Y eso cambia cómo ves tu contrato actual.", apply: (s) => { s.wealth = (s.wealth ?? 0) + 1; rel(s, "agent", 6); rel(s, "fans", -3); flag(s, "tentado_dinero"); } },
    ],
  },
  {
    id: "nb_a_comision",
    kicker: "Números",
    title: "La comisión",
    image: "office",
    category: "agent",
    family: "agent_money",
    requires: (s) => !!s.agent?.present && s.age >= 19,
    text: (s) => `En la última hoja del contrato hay un porcentaje para ${s.agent.name}, tu representante, más alto del que hablasteis. Cuando lo señalas, él no se pone nervioso: se pone didáctico.`,
    choices: [
      { id: "bajar", label: "Exigir el porcentaje pactado", outcome: "Lo baja sin discutir, lo cual dice mucho de lo que intentaba.", apply: (s) => { rel(s, "agent", -6); s.wealth = (s.wealth ?? 0) + 1; flag(s, "controlo_cuentas"); } },
      { id: "abogado", label: "Meter a un abogado independiente", outcome: "Relación más fría, cuentas más limpias.", apply: (s) => { rel(s, "agent", -12); s.wealth = (s.wealth ?? 0) + 2; stat(s, "discipline", 6); flag(s, "controlo_cuentas"); } },
      { id: "firmar", label: "Firmar y no romper la relación", outcome: "Le compras lealtad con dinero. A veces funciona.", apply: (s) => { rel(s, "agent", 10); s.wealth = Math.max(0, (s.wealth ?? 0) - 1); } },
    ],
  },
  {
    id: "nb_a_filtracion",
    kicker: "Prensa",
    title: "Alguien ha filtrado tu cláusula",
    image: "press",
    category: "agent",
    family: "agent_leak",
    requires: (s) => !!s.agent?.present && s.fame >= 25,
    text: (s) => `Sale publicada tu cláusula al euro. Solo tres personas la conocían y una de ellas es ${s.agent.name}, tu representante, que jura por su madre que no ha sido él mientras responde a alguien por WhatsApp.`,
    choices: [
      { id: "encarar", label: "Encararle: \"has sido tú\"", outcome: "No lo niega dos veces. \"Te he subido el precio, chaval.\"", apply: (s) => { rel(s, "agent", -8); stat(s, "fame", 8); flag(s, "filtracion"); conflict(s, "Tu agente filtró tu cláusula"); } },
      { id: "aprovechar", label: "Aprovechar el ruido y callar", outcome: "El club se pone nervioso. Tu valor sube.", apply: (s) => { stat(s, "fame", 10); rel(s, "coach", -4); flag(s, "filtracion"); } },
      { id: "desmentir", label: "Desmentirlo públicamente", outcome: "Nadie te cree del todo, pero el club respira.", apply: (s) => { rel(s, "coach", 6); rel(s, "fans", 5); stat(s, "fame", -2); } },
    ],
  },
  {
    id: "nb_a_cambio_agente",
    kicker: "Decisión",
    title: "Otro representante te busca",
    image: "office",
    category: "agent",
    family: "agent_switch",
    requires: (s) => s.age >= 19 && (s.rel.agent <= 55 || (s.flags["filtracion"] ?? 0) === 1),
    text: () => `Traje mejor, oficina mejor, sonrisa mejor. Una agencia grande te invita a comer y te enseña una lista de clientes que impresiona. "Con nosotros no tendrías que llamar tú nunca."`,
    choices: [
      { id: "cambiar", label: "Cambiar de representante", outcome: "Ruptura fea, mercado más ancho.", apply: (s) => { if (s.agent) { s.agent.firedCount += 1; s.agent.trust = 40; s.agent.name = "Marina Sedano"; } rel(s, "agent", -20); stat(s, "fame", 4); conflict(s, "Cambiaste de representante"); note(s, "Cambias de representante.", "neutral"); } },
      { id: "fiel", label: "Quedarte con el tuyo", outcome: "Se lo cuentas y casi se emociona. Casi.", apply: (s) => { rel(s, "agent", 14); promise(s, "Prometiste lealtad a tu agente"); } },
      { id: "usar", label: "Usar la oferta para renegociar comisión", outcome: "Funciona, pero ya no os miráis igual.", apply: (s) => { rel(s, "agent", -5); s.wealth = (s.wealth ?? 0) + 1; flag(s, "controlo_cuentas"); } },
    ],
  },
  {
    id: "nb_a_presion_renovar",
    kicker: "Renovación",
    title: "Firma ya, dice todo el mundo",
    image: "office",
    category: "agent",
    family: "agent_renew",
    requires: (s) => s.age >= 19 && s.stage !== "youth",
    text: (s) => `El club quiere que firmes esta semana. ${s.agent.name}, tu representante, quiere que esperes a junio. ${who(s, "coach")} te para en el pasillo y te dice que él te quiere aquí. Todos empujan y ninguno paga tus decisiones.`,
    choices: [
      { id: "firmar", label: "Firmar ahora y dormir tranquilo", outcome: "Seguridad, menos dinero, cero ruido.", apply: (s) => { s.contractYears = Math.max(s.contractYears ?? 1, 3); rel(s, "coach", 8); rel(s, "fans", 7); rel(s, "agent", -7); promise(s, "Prometiste quedarte al firmar"); } },
      { id: "esperar", label: "Esperar a junio", outcome: "Seis meses de preguntas en cada rueda de prensa.", apply: (s) => { rel(s, "agent", 9); rel(s, "fans", -6); stat(s, "fame", 5); flag(s, "contrato_en_el_aire"); } },
      { id: "condiciones", label: "Firmar solo con cláusula de salida realista", outcome: "El club refunfuña y acepta. Es la opción de los que piensan a tres años.", apply: (s) => { s.contractYears = Math.max(s.contractYears ?? 1, 3); rel(s, "agent", 5); rel(s, "coach", 3); flag(s, "clausula_salida"); } },
    ],
  },
  {
    id: "nb_a_club_secreto",
    kicker: "Secreto",
    title: "Una reunión que no existe",
    image: "travel",
    category: "agent",
    family: "agent_secret",
    requires: (s) => s.age >= 19 && !!s.agent?.present && s.overall >= 68,
    text: (s) => `Hotel de aeropuerto, sala sin ventanas, dos directivos que no dicen de dónde vienen. ${s.agent.name}, tu representante, insiste: "Si alguien pregunta, hoy has ido al fisio".`,
    choices: [
      { id: "ir", label: "Ir y escuchar", outcome: "Sales con una carpeta y una sensación rara en el estómago.", apply: (s) => { rel(s, "agent", 8); flag(s, "reunion_secreta"); stat(s, "morale", 3); } },
      { id: "condicion", label: "Ir, pero avisando al club", hint: "Transparencia total", outcome: "El club lo agradece. La reunión se enfría sola.", apply: (s) => { rel(s, "coach", 10); rel(s, "fans", 5); rel(s, "agent", -10); } },
      { id: "no", label: "No ir", outcome: "Tu agente tarda una semana en volver a llamarte.", apply: (s) => { rel(s, "agent", -12); stat(s, "discipline", 5); } },
    ],
  },
  {
    id: "nb_a_conflicto",
    kicker: "Ruptura",
    title: "Tu agente habla por ti sin permiso",
    image: "press",
    category: "agent",
    family: "agent_conflict",
    requires: (s) => !!s.agent?.present && ((s.flags["cheque_blanco"] ?? 0) === 1 || s.rel.agent >= 70),
    text: (s) => `Titular: "El entorno del jugador admite que quiere salir". Tú no has dicho eso. ${s.agent.name}, tu representante, sí.`,
    choices: [
      { id: "desmentir", label: "Desmentirlo tú mismo, con nombre y apellidos", outcome: "La afición te aplaude; tu agente te llama diecisiete veces.", apply: (s) => { rel(s, "fans", 12); rel(s, "coach", 7); rel(s, "agent", -15); s.flags["cheque_blanco"] = 0; } },
      { id: "tapar", label: "No desmentir nada", outcome: "El silencio confirma. El estadio lo interpreta solo.", apply: (s) => { rel(s, "fans", -12); stat(s, "fame", 6); flag(s, "quiere_salir"); } },
      { id: "romper", label: "Romper la relación ahí mismo", outcome: "Te quedas sin agente en plena temporada. Valiente y caro.", apply: (s) => { if (s.agent) { s.agent.present = false; s.agent.firedCount += 1; } rel(s, "agent", -25); stat(s, "morale", -5); conflict(s, "Despediste a tu agente por hablar por ti"); } },
    ],
  },
];

/* -------------------------- PRENSA Y AFICIÓN ----------------------------- */
const PRESS: GameEvent[] = [
  {
    id: "nb_p_titular_injusto",
    kicker: "Portada",
    title: "Un titular que no dijiste",
    image: "press",
    category: "press",
    family: "press_quote",
    requires: (s) => s.fame >= 15,
    text: (s) => `"${nick(s)}: 'esta afición no acompaña'". Lo que dijiste fue que el campo estaba frío en la primera parte. Lo que se lee es otra cosa distinta.`,
    choices: [
      { id: "audio", label: "Publicar el audio completo", outcome: "El periodista queda retratado. Y no lo olvida.", apply: (s) => { rel(s, "fans", 10); stat(s, "fame", 5); npcMood(s, "press", -15); flag(s, "guerra_prensa"); } },
      { id: "disculpa", label: "Pedir perdón aunque no sea tuyo", outcome: "Se apaga rápido. Te queda mal cuerpo.", apply: (s) => { rel(s, "fans", 6); stat(s, "morale", -4); rel(s, "coach", 4); } },
      { id: "nada", label: "No decir nada y jugar", outcome: "Dos días de ruido y un partido que lo tapa todo.", apply: (s) => { stat(s, "form", 4); rel(s, "fans", -3); } },
    ],
  },
  {
    id: "nb_p_pitada",
    kicker: "Grada",
    title: "Te pitan al salir",
    image: "stadium",
    category: "press",
    family: "crowd_reaction",
    requires: (s) => s.rel.fans <= 55 && s.stage !== "youth",
    text: () => `Minuto 63, cambio, y el estadio decide que hoy le toca a alguien. Ese alguien eres tú. Los pitos duran hasta que te sientas.`,
    choices: [
      { id: "aplaudir", label: "Aplaudir a la grada mientras te pitan", outcome: "Media grada cambia de opinión sobre la marcha.", apply: (s) => { rel(s, "fans", 8); stat(s, "morale", -3); } },
      { id: "gesto", label: "Hacer un gesto de \"venga, más fuerte\"", hint: "Se puede liar", outcome: "Se lía. Tertulias, portadas y una multa interna.", apply: (s) => { rel(s, "fans", -14); stat(s, "fame", 10); rel(s, "coach", -6); conflict(s, "Te encaraste con la grada"); } },
      { id: "cabizbajo", label: "Sentarte con la toalla en la cabeza", outcome: "La foto sale en todos lados. Da pena y da simpatía a partes iguales.", apply: (s) => { stat(s, "morale", -8); rel(s, "fans", 3); } },
    ],
  },
  {
    id: "nb_p_cantico",
    kicker: "Grada",
    title: "Tienen un cántico para ti",
    image: "stadium",
    category: "press",
    family: "crowd_reaction",
    requires: (s) => s.rel.fans >= 62 && s.fame >= 25,
    text: (s) => `Minuto 20 y el fondo canta tu nombre con una melodía que reconoces de una canción de verano. Suena ridícula. Suena a que ya eres de aquí. ${nick(s)} tarda tres segundos en tragar saliva.`,
    choices: [
      { id: "cantar", label: "Cantarlo con ellos al acabar", outcome: "Se hace vídeo del año en el club.", apply: (s) => { rel(s, "fans", 12); stat(s, "morale", 10); stat(s, "fame", 5); } },
      { id: "escudo", label: "Señalar el escudo", outcome: "Clásico y efectivo.", apply: (s) => { rel(s, "fans", 8); rel(s, "coach", 3); } },
    ],
  },
  {
    id: "nb_p_provocacion",
    kicker: "Sala de prensa",
    title: "El periodista que te busca",
    image: "press",
    category: "press",
    family: "press_duel",
    requires: (s) => s.fame >= 20,
    text: (s) => `${who(s, "press")} levanta la mano el último y pregunta con media sonrisa: "¿No cree que el club se ha equivocado apostando por usted?". Hay doce grabadoras encendidas.`,
    choices: [
      { id: "elegante", label: "Responder con elegancia y datos", outcome: "Le desmontas sin subir la voz. Queda muy bien.", apply: (s) => { stat(s, "fame", 6); rel(s, "coach", 5); npcMood(s, "press", 5); } },
      { id: "ironia", label: "Contestar con ironía", outcome: "Titular garantizado y un enemigo permanente.", apply: (s) => { stat(s, "fame", 10); npcMood(s, "press", -12); rel(s, "coach", -3); flag(s, "guerra_prensa"); } },
      { id: "levantarse", label: "Levantarte y marcharte", outcome: "Nadie olvida esa silla vacía.", apply: (s) => { stat(s, "fame", 8); rel(s, "fans", -6); rel(s, "coach", -8); conflict(s, "Abandonaste una rueda de prensa"); } },
    ],
  },
  {
    id: "nb_p_meme",
    kicker: "Redes",
    title: "Tu cara es un meme",
    image: "press",
    category: "gossip",
    family: "viral",
    requires: (s) => s.fame >= 18,
    text: () => `Un plano tuyo con cara de absoluta incomprensión tras un fuera de juego se ha convertido en plantilla nacional. Ya lo ha usado hasta una cadena de supermercados.`,
    choices: [
      { id: "sumarse", label: "Usar el meme como foto de perfil", outcome: "Ganas cien mil seguidores y un patrocinio pequeño.", apply: (s) => { stat(s, "fame", 12); s.wealth = (s.wealth ?? 0) + 1; rel(s, "fans", 6); } },
      { id: "ignorar", label: "Ignorarlo por completo", outcome: "En dos semanas ya no se acuerda nadie.", apply: (s) => { stat(s, "discipline", 4); stat(s, "fame", -1); } },
      { id: "molesto", label: "Pedir que dejen de usarlo", outcome: "Peor: ahora hay memes sobre tu enfado.", apply: (s) => { stat(s, "fame", 6); stat(s, "morale", -5); rel(s, "fans", -3); } },
    ],
  },
  {
    id: "nb_p_fuera_contexto",
    kicker: "Radio",
    title: "Sacado de contexto",
    image: "press",
    category: "press",
    family: "press_quote",
    requires: (s) => s.fame >= 22 && s.stage !== "youth",
    text: (s) => `Dijiste que en ${short(s)} "hay que dar un paso más si queremos algo grande". Se ha convertido en "el crack pide fichajes y señala a la directiva".`,
    choices: [
      { id: "aclarar", label: "Aclararlo en el siguiente entrenamiento abierto", outcome: "Se calma. El presidente lo agradece por WhatsApp.", apply: (s) => { rel(s, "fans", 5); rel(s, "coach", 5); } },
      { id: "mantener", label: "Mantenerlo: es lo que piensas", outcome: "El vestuario te aplaude por dentro. Arriba, no.", apply: (s) => { rel(s, "dressing", 9); rel(s, "fans", 4); flag(s, "señale_directiva"); conflict(s, "Señalaste a la directiva en público"); } },
      { id: "silencio_prensa", label: "Anunciar que no hablas en un mes", outcome: "Silencio absoluto. Y mucho más ruido alrededor.", apply: (s) => { stat(s, "fame", 7); npcMood(s, "press", -10); stat(s, "form", 3); } },
    ],
  },
  {
    id: "nb_p_redes_noche",
    kicker: "02:10",
    title: "El tuit a medianoche",
    image: "press",
    category: "gossip",
    family: "social_media",
    requires: (s) => s.age >= 17,
    text: () => `Tienes el tuit escrito. Es bueno, es hiriente y contesta a todos los que llevan una semana dándote. El dedo está encima de "Publicar" desde hace cuatro minutos.`,
    choices: [
      { id: "publicar", label: "Publicarlo", outcome: "12.000 retuits antes del desayuno y una llamada del club antes del café.", apply: (s) => { stat(s, "fame", 12); rel(s, "fans", 4); rel(s, "coach", -8); flag(s, "tuit_polemico"); } },
      { id: "borrar", label: "Borrarlo y dejar el móvil en otra habitación", outcome: "Duermes. Ganas.", apply: (s) => { stat(s, "discipline", 7); stat(s, "morale", 4); } },
      { id: "enviar", label: "Enviárselo solo a un amigo", outcome: "Tu amigo hace captura. La captura viaja.", apply: (s) => { stat(s, "fame", 5); rel(s, "dressing", -3); flag(s, "captura_fuera"); } },
    ],
  },
];

/* ---------------------- PARTIDOS CLAVE (post-partido) --------------------- */
const MATCHKEY: GameEvent[] = [
  {
    id: "nb_m_error_grave",
    kicker: "Después del error",
    title: "El fallo que se va a repetir mil veces",
    image: "match",
    category: "life",
    family: "match_aftermath",
    requires: (s) => s.stage !== "youth" && s.form <= 58,
    text: (s) => `Tu error dio el gol. En el vestuario nadie te mira mal, que es peor. ${who(s, "captain")} pasa por detrás y te aprieta el hombro sin decir nada.`,
    choices: [
      { id: "cara", label: "Salir a dar la cara ante la prensa", outcome: "\"Es mío. No busquen a otro.\" El club respira, tú no.", apply: (s) => { rel(s, "fans", 9); rel(s, "dressing", 8); stat(s, "morale", -4); stat(s, "fame", 4); } },
      { id: "video", label: "Pedir el vídeo y verlo esa misma noche", outcome: "Cuarenta veces la misma jugada. Duele y enseña.", apply: (s) => { stat(s, "overall", 2); stat(s, "morale", -6); stat(s, "form", 4); } },
      { id: "desconectar", label: "Apagar el móvil tres días", outcome: "Vuelves más entero, aunque hayan hablado sin ti.", apply: (s) => { stat(s, "morale", 7); stat(s, "fame", -3); } },
    ],
  },
  {
    id: "nb_m_penalti",
    kicker: "Minuto 89",
    title: "¿Coges tú el penalti?",
    image: "stadium",
    category: "life",
    family: "match_pressure",
    requires: (s) => s.stage !== "youth" && s.age >= 17,
    text: (s) => `Penalti a favor, empate, minuto 89. El lanzador titular está en el banquillo. Cuatro compañeros miran el balón y luego te miran a ti. ${nick(s)} nota el corazón en la garganta.`,
    choices: [
      { id: "tirar", label: "Coger el balón", hint: "Todo o nada", outcome: "Gol. Estadio en pie. Duermes flotando.", apply: (s) => { stat(s, "form", 12); rel(s, "fans", 12); stat(s, "fame", 8); stat(s, "morale", 10); milestone(s, "Marcaste un penalti decisivo en el 89'."); } },
      { id: "ceder", label: "Cedérselo al veterano que lo pide", outcome: "Lo falla. Nadie te culpa. Tú sí, un poco.", apply: (s) => { rel(s, "dressing", 6); stat(s, "morale", -5); } },
      { id: "arbitro", label: "Pedir al míster desde el campo que decida él", outcome: "Pierdes treinta segundos y algo de respeto.", apply: (s) => { rel(s, "coach", -5); rel(s, "dressing", -4); } },
    ],
  },
  {
    id: "nb_m_expulsion",
    kicker: "Roja",
    title: "Te vas expulsado",
    image: "match",
    category: "life",
    family: "match_aftermath",
    requires: (s) => s.stage !== "youth" && s.discipline <= 72,
    text: () => `Segunda amarilla por protestar algo que ni siquiera era contra ti. Camino del túnel te da tiempo a arrepentirte tres veces y a cabrearte cuatro.`,
    choices: [
      { id: "esperar", label: "Esperar al equipo en el vestuario y pedir perdón", outcome: "El grupo lo valora. La sanción sigue.", apply: (s) => { rel(s, "dressing", 8); stat(s, "discipline", 6); rel(s, "coach", 3); } },
      { id: "ducha", label: "Ducharte e irte antes de que acaben", outcome: "El míster lo ve. No lo comenta. Lo apunta.", apply: (s) => { rel(s, "coach", -9); rel(s, "dressing", -6); stat(s, "morale", -3); } },
      { id: "arbitro2", label: "Buscar al árbitro al final", hint: "Muy mala idea", outcome: "Dos partidos más de sanción por el acta.", apply: (s) => { stat(s, "discipline", -12); rel(s, "coach", -10); conflict(s, "Buscaste al árbitro tras una expulsión"); note(s, "Sanción ampliada por el acta arbitral.", "bad"); } },
    ],
  },
  {
    id: "nb_m_suplencia_derbi",
    kicker: "Derbi",
    title: "Suplente en el partido del año",
    image: "tunnel",
    category: "life",
    family: "match_pressure",
    requires: (s) => s.stage !== "youth" && s.age >= 18,
    text: (s) => `Semana de derbi. Todo el mundo en la ciudad te ha preguntado si juegas. En la charla, ${npcName(s, "coach")}, tu entrenador, no dice tu nombre en el once. Silencio de nueve segundos.`,
    choices: [
      { id: "calentar", label: "Ser el que más calienta y el que más anima", outcome: "Sales en el 70' con el estadio de tu lado.", apply: (s) => { rel(s, "coach", 8); rel(s, "dressing", 7); stat(s, "form", 5); } },
      { id: "frio", label: "Sentarte y no aplaudir nada", outcome: "Las cámaras cogen tu cara justo en el gol del equipo.", apply: (s) => { rel(s, "dressing", -8); rel(s, "fans", -6); stat(s, "morale", -4); flag(s, "cara_larga"); } },
      { id: "hablar", label: "Pedirle explicaciones antes del partido", outcome: "\"Hoy no, ¿vale? Hoy no.\"", apply: (s) => { rel(s, "coach", -6); stat(s, "morale", 3); } },
    ],
  },
  {
    id: "nb_m_gol_importante",
    kicker: "Gol",
    title: "El gol que cambia el mes",
    image: "celebration",
    category: "life",
    family: "match_aftermath",
    requires: (s) => s.stage !== "youth" && s.form >= 58,
    text: (s) => `Le has dado tres puntos al ${short(s)} en el descuento. En el césped no sabes ni cómo celebrar: acabas corriendo hacia el banderín sin plan.`,
    choices: [
      { id: "grada", label: "Dedicárselo al fondo", outcome: "El fondo lo devuelve durante veinte minutos.", apply: (s) => { rel(s, "fans", 12); stat(s, "fame", 6); stat(s, "morale", 8); } },
      { id: "banquillo", label: "Correr hacia el banquillo y abrazar al míster", outcome: "Imagen del día. Y un entrenador que ahora te defiende siempre.", apply: (s) => { rel(s, "coach", 12); rel(s, "dressing", 5); } },
      { id: "familia", label: "Señalar a la grada donde está tu familia", outcome: "Tu madre llora en directo en televisión.", apply: (s) => { rel(s, "family", 14); stat(s, "morale", 12); } },
    ],
  },
  {
    id: "nb_m_publico_contra",
    kicker: "Campo hostil",
    title: "Un estadio entero contra ti",
    image: "stadium",
    category: "life",
    family: "match_pressure",
    requires: (s) => s.fame >= 30 && s.stage !== "youth",
    text: () => `Cada vez que tocas el balón, cuarenta mil personas silban a la vez. El calentamiento ha sido una lluvia de insultos creativos y un mechero que ha caído lejos.`,
    choices: [
      { id: "silencio", label: "Callarlos con fútbol", outcome: "Asistencia y gol. El silencio final se disfruta más que el gol.", apply: (s) => { stat(s, "form", 10); stat(s, "fame", 8); rel(s, "fans", 6); } },
      { id: "provocar", label: "Provocarles al celebrar", outcome: "Amarilla, expediente y un vídeo eterno.", apply: (s) => { stat(s, "fame", 12); stat(s, "discipline", -8); rel(s, "coach", -6); } },
      { id: "encogerse", label: "Jugar a lo fácil y no aparecer", outcome: "Sobrevives al partido. El míster ve el partido entero.", apply: (s) => { stat(s, "form", -6); rel(s, "coach", -5); } },
    ],
  },
  {
    id: "nb_m_partido_horrible",
    kicker: "Autocrítica",
    title: "El peor partido de tu vida",
    image: "locker",
    category: "life",
    family: "match_aftermath",
    requires: (s) => s.stage !== "youth" && s.form <= 50,
    text: () => `Cuarenta minutos, cero pases acertados en campo contrario, cambio antes del descanso. En la ducha te quedas de pie con el agua fría más tiempo del necesario.`,
    choices: [
      { id: "gimnasio", label: "Ir al gimnasio esa misma noche", outcome: "No arregla nada, pero te devuelve el control.", apply: (s) => { stat(s, "fitness", 6); stat(s, "form", 4); rel(s, "coach", 3); } },
      { id: "llorar", label: "Llamar a casa y romperte", outcome: "Media hora al teléfono. Al colgar, respiras distinto.", apply: (s) => { rel(s, "family", 10); stat(s, "morale", 9); } },
      { id: "salir", label: "Salir de fiesta a olvidarlo", outcome: "Alguien te graba a las cuatro. Y el club lo ve.", apply: (s) => { stat(s, "morale", 4); stat(s, "fitness", -8); rel(s, "coach", -7); stat(s, "fame", 4); flag(s, "fiesta_pillada"); } },
    ],
  },
  {
    id: "nb_m_debut_visto",
    kicker: "Grada",
    title: "Tu familia en su primer partido tuyo de verdad",
    image: "stadium",
    category: "life",
    family: "family_pride",
    requires: (s) => s.stage !== "youth" && s.age <= 24,
    text: (s) => `Tu padre nunca viaja. Hoy ha cogido un autobús de seis horas y está en la grada con una bufanda del ${short(s)} que le queda enorme y que no piensa quitarse.`,
    choices: [
      { id: "camiseta", label: "Darle tu camiseta al acabar", outcome: "No la lava nunca. Literalmente.", apply: (s) => { rel(s, "family", 15); stat(s, "morale", 10); } },
      { id: "cena", label: "Llevarles a cenar aunque haya recuperación", outcome: "Cuatro horas de sobremesa y un fisio enfadado.", apply: (s) => { rel(s, "family", 12); stat(s, "fitness", -4); stat(s, "morale", 8); } },
      { id: "concentrado", label: "Saludar de lejos y seguir la rutina", outcome: "Él lo entiende. Tú te quedas con la espina.", apply: (s) => { stat(s, "discipline", 6); rel(s, "family", -4); } },
    ],
  },
];

export const BANK_CLUB: GameEvent[] = [...COACH, ...DRESSING, ...AGENT, ...PRESS, ...MATCHKEY];
export { hasTrait, injure };
