/**
 * Cachondeo de vestuario: el humor de verdad de un grupo de veinte tíos que
 * conviven más horas que con su familia. Novatadas, apuestas, supersticiones,
 * apodos. Casi todas son sueltas, pero varias dejan una marca que vuelve
 * (el apodo que adopta la grada, la apuesta que se cobra).
 */
import { S, o, r, after } from "../dsl";
import type { BankScene } from "../types";

export const CACHONDEO_VESTUARIO: BankScene[] = [
  S("cv-novatada-cancion", "humor", { minAge: 16, maxAge: 22, roles: ["suplente", "rotacion", "titular"], clubTurns: [1, 14] }, "vestuario",
    "Te toca cantar en el autobús",
    "Es la tradición: el último en llegar al primer equipo canta en el viaje de vuelta, de pie en el pasillo, con el autobús cogiendo curvas. Un veterano ya ha sacado el móvil para grabar y el capitán decide el tema sin consultarte: «Algo de tu pueblo, para que lloren». Todo el autobús calla de golpe, como un estadio antes de un penalti.",
    [
      o("a", "Cantar con todas tus fuerzas, aunque desafines", "Entregarte al ridículo", { rel_vestuario: 6, moral: 4, fama: 1 }, "Cantas una jota que aprendiste de tu abuelo y desafinas en cada nota. A mitad de la segunda estrofa, el autobús entero te acompaña con palmas. El lateral te pone una mano en el hombro: «Ya eres uno de los nuestros»."),
      o("b", "Negarte con una broma y pagar una ronda", "Salir del paso con humor", { rel_vestuario: 2, patrimonio: -120, moral: 1 }, "Dices que prefieres pagar con dinero que con dignidad, y la ronda te sale por ciento veinte euros en un área de servicio. Te aplauden sin entusiasmo, pero te perdonan."),
      o("c", "Pedirle al capitán que cante él primero", "Plantar cara con sonrisa", { rel_vestuario: 3, reputacion: 1 }, "El capitán te mira un segundo con las cejas arriba y entonces, para sorpresa de todos, se levanta y canta él. Es horroroso. Es inolvidable. Te quita del medio para siempre."),
    ]),
  S("cv-calcetin", "humor", { minAge: 17, clubTurns: [2, 200] }, "vestuario",
    "El misterio del calcetín desaparecido",
    "Antes de salir al campo, el utillero entra en el vestuario con cara de funeral: falta un calcetín del lote del partido. Uno. El del extremo izquierdo. Nadie sabe cómo, nadie sabe cuándo, pero el míster ya ha dicho «aquí hay que descubrir quién ha sido», como si fuera una cuestión de Estado.",
    [
      o("a", "Ofrecerte a recorrer el vestuario como detective", "Tomártelo muy en serio", { rel_vestuario: 3, moral: 3 }, "Interrogas a todo el mundo con una linterna del móvil. Descubres que el calcetín está dentro de la bota del propio extremo, que no se había dado cuenta. El vestuario te hace una ovación burlona y tú saludas."),
      o("b", "Prestar uno de los tuyos y no dar importancia", "Resolver sin dramas", { rel_vestuario: 2, rel_entrenador: 1 }, "Le das un calcetín tuyo, todavía caliente. «Esto no se olvida», murmura el extremo. Y no se olvida: la semana siguiente te lo devuelve lavado y con una nota con corazones."),
      o("c", "Ironizar sobre el utillero delante de todos", "Un chiste a su costa", { rel_vestuario: 1, moral: 1, rel_entrenador: -1 }, "Haces un comentario sobre «las desapariciones de ropa del Gobierno» y el utillero te mira con una frialdad que te pone la piel de gallina. Tendrás que llevarte bien con él si quieres botas limpias."),
    ]),
  S("cv-porra", "humor", { minAge: 18, patrimonio: [300, 100000000], roles: ["titular", "rotacion", "suplente"] }, "vestuario",
    "La porra de la Liga del vestuario",
    "Alguien ha colgado una hoja en la pared del vestuario: «PORRA DE LA LIGA. 20 € por cabeza. Quien acierte la posición final del equipo, se lleva el bote. Quien falle por más de cinco puestos, friega los platos en la cena de Navidad». Tu nombre aparece ya, escrito con rotulador, junto a un 4 que no recuerdas haber elegido.",
    [
      r("a", "Apostar por el campeón, a lo grande", "Ir a por el bote", 0.4, "Aciertas el campeón y el bote es de los grandes. Te lo embolsas entre abucheos fingidos y alguien graba un vídeo con el título «El vidente del vestuario».", { patrimonio: 380, rel_vestuario: 2, moral: 4 }, "Te equivocas por siete puestos. En la cena de Navidad te ponen un delantal con tu nombre y friegas hasta las once, entre risas.", { rel_vestuario: 3, moral: -1 }, "reputacion"),
      o("b", "Apostar prudente, a la mitad de la tabla", "Sin arriesgar", { patrimonio: -20, moral: 1 }, "Pones un número gris y sin gracia. El vestuario te llama «el notario», pero no te toca fregar. Se ríen de ti a tu cara, y tú te ríes con ellos."),
      o("c", "No jugar: no apuestas con compañeros", "Marcar tu línea", { rel_vestuario: -2, reputacion: 1 }, "Dices que prefieres no mezclar dinero y vestuario. Te dejan en paz, pero durante tres días te llaman «el abstemio» en los mensajes del grupo."),
    ]),
  S("cv-portero-botas", "humor", { minAge: 17, clubTurns: [3, 200] }, "vestuario",
    "El portero y sus supersticiones",
    "El portero titular lleva tres años sin lavarse el guante izquierdo «porque no hemos perdido en casa con él». Hoy el fisio lo ha cogido con unas pinzas, lo ha metido en una bolsa de plástico y le ha dado una charla de higiene. El portero lo mira como quien ve cómo se llevan a su hijo.",
    [
      o("a", "Defender al portero con un discurso falso de ciencia", "Ponerte de su parte", { rel_vestuario: 4, moral: 2, reputacion: -1 }, "Citas un estudio inventado de una universidad inexistente y el portero casi llora. El fisio te mira como si le debieras una disculpa a la medicina."),
      o("b", "Ponerte del lado del fisio", "El guante apesta", { rel_vestuario: -2, reputacion: 2, moral: 1 }, "Le cuentas al portero que eso no es ciencia, es olor. El portero te señala con el dedo, muy digno: «Esta semana te vas a comer un gol». La semana siguiente, le marcan un gol a él."),
      o("c", "Regalarle un guante nuevo y que lo ensucie él", "Mediación con gracia", { rel_vestuario: 3, patrimonio: -60 }, "El portero ensucia el guante nuevo con tierra del campo de entrenamiento y lo exhibe orgulloso. El fisio levanta las dos manos al cielo, sin palabras."),
    ]),
  S("cv-autobus-asientos", "humor", { minAge: 19, clubTurns: [4, 300], rel: { vestuario: [30, 100] } }, "vestuario",
    "Quién se sienta con quién en el autobús",
    "En el vestuario hay una ley no escrita: los asientos del autobús tienen dueño. El del fondo, los veteranos; el de la ventanilla delante, el portero; el del medio, los que juegan a las cartas. Hoy, sin querer, te has sentado en el sitio del capitán. Nadie dice nada. Pero nadie dice nada con mucha intensidad.",
    [
      o("a", "Levantarte y pedir perdón, con humor", "Admitir el error", { rel_vestuario: 3, reputacion: 1 }, "Te levantas con una reverencia. El capitán sonríe satisfecho y se sienta con mucha dignidad. Durante un mes te llamarán «el que se sentó en el trono»."),
      o("b", "Quedarte y fingir que no te has enterado", "Jugártela", { rel_vestuario: -3, moral: 2 }, "Haces como que miras por la ventana. El capitán se sienta en el asiento de al lado, sin una palabra, y durante todo el viaje hace comentarios sobre ti en un idioma inventado."),
      o("c", "Proponer una votación para renovar los asientos", "Revolución democrática", { rel_vestuario: 4, reputacion: 1, rel_entrenador: -1 }, "La votación acaba en una discusión de tres cuartos de hora y un acuerdo ridículo: rotar cada mes. El míster, desde la primera fila, se pone los auriculares."),
    ]),
  S("cv-grupo-nombre", "humor", { minAge: 17, clubTurns: [2, 400] }, "vestuario",
    "La guerra del nombre del grupo",
    "El grupo de WhatsApp del equipo cambia de nombre cada cuatro horas: «Los Galácticos del Barrio», «Club de la Comedia FC», «Los Culés Tristes» (ofensivo, retirado), «Cena 20:30» (por error de un lateral). Tu móvil vibra sesenta veces antes del desayuno. Alguien te señala en el chat: «Tú que escribes bonito, ponle nombre definitivo».",
    [
      o("a", "Proponer un nombre con ironía fina", "Un título que haga reír", { rel_vestuario: 4, moral: 3 }, "Pones «Los Tres Puntos Primero». El grupo lo aprueba con veintitrés emojis de aplauso y el míster, que está en el grupo sin que nadie lo sepa, le pone un corazón."),
      o("b", "Silenciar el grupo durante una semana", "Paz mental", { moral: 2, rel_vestuario: -2 }, "Pones el grupo en silencio. Una semana después hay seiscientos mensajes sin leer y tres chistes sobre ti que no entiendes porque te falta el contexto."),
      o("c", "Convertirte en el moderador y poner normas", "El orden, ante todo", { rel_vestuario: -1, reputacion: 2 }, "Redactas tres normas con cabeza. El grupo te nombra «Ministro de Orden» y empieza a borrar mensajes tuyos. A los dos días, tienes más enemigos que nunca."),
    ]),
  S("cv-amigo-invisible", "humor", { turn: [3, 5], minAge: 17, clubTurns: [3, 400] }, "vestuario",
    "El amigo invisible de Navidad",
    "El capitán ha organizado el amigo invisible con una única regla: máximo cincuenta euros y, sobre todo, nada de camisetas. Te ha tocado el delantero centro que se queja de todo, el que critica la música, el menú del hotel y hasta la temperatura del agua. Tienes que comprarle algo que le guste. Algo.",
    [
      o("a", "Regalarle unos auriculares con cancelación de ruido", "Que se calle un poco", { patrimonio: -50, rel_vestuario: 3, moral: 2 }, "Cuando abre el paquete, se pone los auriculares y el vestuario entero dice «por fin». Él, con cara de profunda felicidad, ni se entera de que se ríen."),
      o("b", "Regalarle un libro de autoayuda con dedicatoria", "Una indirecta elegante", { patrimonio: -20, rel_vestuario: 4, moral: 3 }, "Le pones: «Para que veas que la vida también tiene cosas buenas». El delantero lo lee en voz alta, se ríe sin querer y dice «cabrón» con mucho cariño."),
      o("c", "Gastar mucho, a lo grande y sin gracia", "Un reloj caro y a otra cosa", { patrimonio: -480, rel_vestuario: 1, reputacion: 1 }, "Se queda mudo un segundo, y después dice «esto es demasiado, ¿qué quieres?». Le dices que nada, y él, sospechando, te mira recelando hasta Año Nuevo."),
    ]),
  S("cv-tupper", "humor", { minAge: 17, maxAge: 25, clubTurns: [1, 30] }, "vestuario",
    "El tupper del lateral",
    "Cada martes, el lateral derecho trae un tupper con algo que huele a abuela, a cocido y a poder absoluto. No lo comparte con nadie. Hoy, por primera vez, te mira, destapa un poco el recipiente y dice solo: «¿Quieres?». En el vestuario, el resto de la plantilla contiene la respiración: es un honor que nadie había recibido.",
    [
      o("a", "Aceptar y probar un bocado", "Aceptar el regalo", { rel_vestuario: 5, moral: 4, forma: 1 }, "Es el mejor cocido que has comido en tu vida. El lateral te mira con orgullo. Desde ese día, cada martes te guarda una cucharada, y los demás te envidian con el alma."),
      o("b", "Decir que ya has comido, con tacto", "Rechazar con cariño", { rel_vestuario: -1 }, "Dices que has comido ya, que no tienes hambre. El lateral cierra el tupper con delicadeza. Nadie dice nada. Pero algo, en esa mirada, se enfría."),
      o("c", "Aceptar el tupper entero con una sonrisa traviesa", "Provocar un poco", { rel_vestuario: 2, moral: 3 }, "Te lo llevas bajo el brazo con la excusa de «cenar algo bueno». El lateral te sigue por el pasillo diciendo «¡Eh, eh, eh!» y nadie sabe si va a pegarte o a abrazarte."),
    ]),
  S("cv-barba-apuesta", "humor", { minAge: 18, clubTurns: [4, 400] }, "vestuario",
    "La apuesta de las barbas",
    "El central y el pivote han hecho una apuesta absurda: el primero que pierda un partido, se afeita la barba delante de todos. El equipo lleva cuatro victorias seguidas y las barbas tienen ya vida propia. Ayer, el central vino con un peine de madera. Hoy hay una racha en juego, un partido difícil y una responsabilidad histórica.",
    [
      o("a", "Salir al campo con un pacto: ganar por la barba", "Unir al grupo", { moral: 4, rel_vestuario: 3, forma: 1 }, "Todo el vestuario sale al campo con una sola idea: no perder. Ganáis 1-0 en el descuento. El central se abraza a su barba en el túnel como a un hijo."),
      o("b", "Aconsejar al pivote que se afeite ya, por salud pública", "Dar la cara por la higiene", { rel_vestuario: -1, moral: 1 }, "El pivote te mira ofendido: «Esta barba es lo único que me queda». Dos días después, un cuarto de la plantilla ha empezado a llevar barba por solidaridad."),
      o("c", "No meterte: es un asunto de honor ajeno", "Dejarles", { rel_vestuario: 1 }, "Te sientas a mirar con un bocadillo. Pierden en la jornada 10 y se afeitan los dos, entre lágrimas de verdad, en el vestuario con todos de público. Es la mejor tarde del año."),
    ]),
  S("cv-padel", "humor", { minAge: 19, patrimonio: [1000, 100000000], clubTurns: [4, 400] }, "vestuario",
    "El torneo de pádel del vestuario",
    "El lateral ha montado un torneo de pádel sin consultar a nadie, con cuadro, trofeo de latón y árbitro (el masajista, con silbato). Las parejas las ha sorteado un sombrero. Te ha tocado con el portero, que juega de forma agresiva y solo sabe decir «¡mía!». El perdedor lava los coches de los ganadores durante una semana.",
    [
      r("a", "Jugar a muerte para ganar", "Competir en serio", 0.5, "Ganáis la final en un partido de infarto. Los perdedores lavan vuestros coches con cara de funeral, y el portero se hace una foto con el trofeo que acaba en la portada interior del periódico local.", { rel_vestuario: 4, moral: 5, forma: 1 }, "Perdéis la final. Te toca lavar cuatro coches un sábado con el sol de justicia, con el masajista dirigiendo con el silbato. Es humillante. Es memorable.", { rel_vestuario: 4, moral: 0 }, "forma"),
      o("b", "Dejar que el portero haga todo y mirar", "Ahorrar fuerzas", { rel_vestuario: -1, forma: 1 }, "Te colocas atrás y el portero juega por los dos con una fe ciega. Os eliminan en cuartos. «No me ayudaste», te dice. «Te cuidé la rodilla», respondes."),
      o("c", "Montar una apuesta paralela con el masajista", "Aprovechar el caos", { patrimonio: -40, rel_vestuario: 2, moral: 2 }, "Apuestas con el masajista a quién gana. Pierdes. Te masajea la espalda con una sonrisa que da escalofríos durante el resto del mes."),
    ]),
  S("cv-musica", "humor", { minAge: 17, clubTurns: [2, 400] }, "vestuario",
    "La guerra de la música del vestuario",
    "Quien lleva el altavoz, manda. Hasta hoy mandaba el lateral con su reguetón de los noventa. Pero esta mañana el míster ha prohibido la música «de la mitad de la plantilla» y ha impuesto una lista cerrada: clásicos de los ochenta, nada de letras explícitas, y una balada de cierre. Hay un vacío de poder en el altavoz y todos te miran.",
    [
      o("a", "Proponer una lista equilibrada con cinco estilos", "Pacificar el vestuario", { rel_vestuario: 4, rel_entrenador: 1, moral: 2 }, "Haces una lista que no deja contento a nadie y por eso funciona. El míster la aprueba con un asentimiento seco. A los diez días, el vestuario baila con una canción de los ochenta como si fuera la final."),
      o("b", "Seguir con el reguetón por la puerta de atrás", "Rebeldía", { rel_vestuario: 3, rel_entrenador: -3 }, "Metes el altavoz en una bolsa de deporte y suena a todo trapo en la ducha. El míster aparece con la cara colorada. «¿Qué es esto?». «La banda sonora de nuestras victorias», dices. Te multa con una pizza."),
      o("c", "Dejar que decida el míster sin discutir", "Disciplina", { rel_entrenador: 3, rel_vestuario: -1 }, "Aceptas la lista del míster. El vestuario te mira como si hubieras vendido el barrio. Pero el míster, al salir, te guiña el ojo: no lo olvidará."),
    ]),
  S("cv-camiseta-reves", "humor", { minAge: 17, roles: ["titular", "rotacion"] }, "partido",
    "Sales al campo con la camiseta al revés",
    "Nadie lo ha visto en el túnel. Ni el utillero, ni el delantero, ni el míster. Pero el árbitro, al pasar lista, te dice con un hilo de voz: «Oye, tienes el escudo por dentro». Estás a diez segundos de salir a veinte mil personas con la camiseta al revés. Hay una cámara apuntándote ahora mismo.",
    [
      o("a", "Quitártela en el túnel y ponértela bien delante de todos", "Dar la cara con humor", { moral: 2, fama: 2, rel_vestuario: 3 }, "Te la quitas y te la pones bien con la cámara enfocando. El estadio ríe al ver las imágenes en la pantalla gigante y te ovaciona. Tu error se convierte en el vídeo más compartido de la semana."),
      o("b", "Salir así y fingir que es un homenaje", "Jugártela", { fama: 3, rel_vestuario: 1, rel_entrenador: -1 }, "Sales con la camiseta al revés y una cara de mármol. Nadie lo ve hasta el minuto doce. Después, el estadio entero grita «¡al revés, al revés!» durante el resto del partido."),
      o("c", "Pedirle al utillero que te traiga otra y esperar", "Prudencia", { rel_entrenador: -1, moral: -1 }, "Llegas tarde al once inicial por salir con otra camiseta. El míster te mira de lado. Por una vez, el error lo has resuelto sin que nadie lo vea. Pero no sale bien."),
    ]),
  S("cv-fisio-ligon", "humor", { minAge: 17, clubTurns: [2, 400] }, "vestuario",
    "El fisio y su club de fans",
    "El fisio es un hombre de cincuenta años con una paciencia infinita y un club de fans que no sabe que tiene. En el vestuario ha empezado una apuesta: cuántas veces al día le dicen «¡qué manos tienes!» las novias, hermanas y madres de los jugadores. Hoy le tocan el hombro a ti. «A ver esa rodilla», dice. Y, por supuesto, hay público.",
    [
      o("a", "Entrar en el juego y darle las gracias con una reverencia", "Seguir la broma", { rel_vestuario: 3, moral: 3 }, "Le dedicas una reverencia de teatro. El fisio, serio, se pone una mano en el pecho y dice «es mi vocación». Todo el vestuario estalla y la apuesta sube un punto."),
      o("b", "Cortar la broma: el fisio es un profesional", "Respetar", { reputacion: 2, rel_vestuario: -1 }, "Les pides que lo dejen en paz. El fisio, en silencio, te mira con una gratitud que te estremece un poco. Esa semana te trata la rodilla con el doble de esmero."),
      o("c", "Contarle al fisio la apuesta para que se divierta", "Ser su cómplice", { rel_vestuario: 2, moral: 2 }, "El fisio se ríe, se ajusta las gafas y esa semana dice «¡qué manos tengo!» antes de que nadie lo diga. Gana la apuesta de calle. Nadie sabe quién ha hablado."),
    ]),
  S("cv-penaltis-utillero", "humor", { minAge: 17, clubTurns: [4, 400] }, "entrenamiento",
    "Una tanda de penaltis contra el utillero",
    "El utillero lleva años diciendo que fue portero en juveniles y nadie lo cree. Hoy, tras un entrenamiento, el míster le da unos guantes y le dice: «A ver si es verdad». El equipo entero forma un semicírculo. Tú, el que tiene mejor tiro del grupo, eres el primero en lanzar. El utillero se ajusta los guantes con una solemnidad ridícula.",
    [
      o("a", "Tirar fuerte, a la escuadra", "Hacer lo normal", { rel_vestuario: 2, moral: 2 }, "Metes el penalti por la escuadra. El utillero ni se mueve. Después, muy serio, dice: «Estaba de mentira». Todo el vestuario se ríe hasta que el míster empieza a llorar de la risa."),
      o("b", "Tirar flojo al centro para que pare", "Dejarle lucirse", { rel_vestuario: 4, moral: 3, reputacion: 1 }, "Lanzas un tiro blandito al centro. El utillero lo para con la cara, el pecho y las rodillas. Cuando se levanta, tiene los brazos en alto como si hubiera ganado el Mundial. Los demás le cantan el himno."),
      o("c", "Tirar un penalti a lo Panenka con una sonrisa", "Una gracia", { rel_vestuario: 2, fama: 1 }, "La picas por el centro con una caricia. El utillero se tira a un lado, solemnemente. El balón lo besa en el trasero cuando se levanta. «Eso es falta», dice con dignidad."),
    ]),
  S("cv-apodo", "humor", { minAge: 17, clubTurns: [2, 300] }, "vestuario",
    "El mote que se te queda",
    "Todo empezó con un chiste sobre cómo corres cuando te persigue un perro. Ahora, en el vestuario, todos te llaman «El Galgo». El míster lo ha escrito en la pizarra por error. El utillero ha cosido un galgo diminuto en tu camiseta de entreno. Y alguien ha filtrado el apodo a un periodista, que ya piensa en un titular.",
    [
      o("a", "Adoptar el apodo con orgullo", "Apropiarte de la broma", { rel_vestuario: 5, fama: 3, moral: 3 }, "Subes una foto con un galgo de peluche y la frase «el apodo manda». Al domingo siguiente, la grada te canta «¡Galgo, Galgo!». Es difícil quitarte el mote de encima en las próximas temporadas."),
      o("b", "Pedir que lo olviden: no te gusta", "Pedir respeto", { rel_vestuario: -2, moral: -1 }, "Les dices que no te gusta. Se calman un día y al siguiente el apodo vuelve, escrito con tiza en tu taquilla. «Cariño», dice el lateral. Ya no hay manera."),
      o("c", "Ponerle tú otro apodo a quien empezó la broma", "Responder con fuego", { rel_vestuario: 4, moral: 2 }, "Le pones «El Hornillo» al que empezó, porque siempre trae algo de comer. El apodo cuaja con más fuerza que el tuyo. Por una vez, el mote ajeno funciona."),
    ], { weight: 1.2 }),
  S("cv-apodo-grada", "humor", { after: [after("cv-apodo", "a", 8, 90)], fama: [20, 100] }, "vestuario",
    "La grada ha adoptado tu mote",
    "Un domingo cualquiera, al calentar, el fondo sur empieza a cantar tu apodo con una melodía que nadie había ensayado. Es un cántico corto y pegadizo y los niños de la grada lo repiten como un himno. En el vestuario, el lateral te mira con los brazos cruzados y una sonrisa que dice «te lo dije». Tienes que decidir qué hacer con la canción.",
    [
      o("a", "Saludar a la grada con la mano en el pecho", "Agradecer el cariño", { rel_aficion: 6, moral: 5, fama: 2 }, "Saludas con la mano en el pecho y la grada estalla. En las siguientes semanas, tu camiseta se agota en la tienda del club, con un galgo en la manga."),
      o("b", "Dedicarles un gol con una celebración del apodo", "Hacerlo tuyo", { rel_aficion: 5, fama: 4, moral: 4 }, "Marcas el domingo siguiente y celebras corriendo con los brazos como un galgo. Los de atrás de la portería corren contigo, y la imagen sale en todas las portadas deportivas."),
    ], { isMilestone: true, milestoneType: "escena", imageScene: "Photorealistic photo of a footballer greeting a roaring crowd in a stadium with a hand on his chest, stands full of fans chanting and waving scarves, golden hour light, emotional sports photography" }),
  S("cv-hotel-sinwifi", "humor", { minAge: 17, clubTurns: [2, 400], roles: ["titular", "rotacion", "suplente"] }, "vestuario",
    "El hotel de concentración sin wifi",
    "El míster ha elegido un hotel de montaña «para desconectar»: sin cobertura, sin wifi y con una recepcionista que parece sacada de una película de miedo. La primera noche, el grupo se reúne en el salón con una baraja y un portátil que alguien consiguió conectar a un cable de la cocina. El míster, desde el pasillo, finge que no lo ve.",
    [
      o("a", "Montar un torneo de cartas con apuestas de lavar platos", "Aprovechar la noche", { rel_vestuario: 5, moral: 4 }, "Os pasáis la noche jugando al mus con el míster de pie en la puerta, dando consejos. A las tres de la mañana, el portero pierde la partida y lava los platos del desayuno con una dignidad inmensa."),
      o("b", "Irte a dormir temprano y descansar", "Cuidar la forma", { forma: 3, moral: 1, rel_vestuario: -1 }, "Te acuestas a las diez. Al día siguiente, el míster te felicita por la cara de descansado. El resto de la plantilla tiene unas ojeras como platos."),
      o("c", "Contar historias de miedo en el pasillo", "Un clásico", { rel_vestuario: 3, moral: 3 }, "Inventas una leyenda del hotel con una recepcionista fantasma. A las doce, el lateral no se atreve a ir al baño solo. A las dos, la recepcionista aparece de verdad detrás de él. Grita como un niño."),
    ]),
  S("cv-fotos-oficiales", "humor", { minAge: 17, turn: [1, 3], clubTurns: [1, 400] }, "vestuario",
    "El día de las fotos oficiales",
    "Una mañana entera de camisetas nuevas, sonrisas forzadas y un fotógrafo que repite «un poco más a la izquierda» sin dejar de mirar el reloj. El portero se niega a posar sin su gorra de la suerte; el lateral está disfrazado de modelo de pasarela; el capitán ha sido sorprendido con una chuleta detrás de la espalda. En tu turno, el fotógrafo te dice: «Pon cara de ganador».",
    [
      o("a", "Posar con una cara de pocos amigos, muy seria", "Intimidar", { fama: 2, rel_vestuario: 2, moral: 1 }, "Sales con una mirada de acero que luego se hace viral como «la cara del míster». La foto sale en la portada del dosier de prensa. Tu madre la enmarca, orgullosa."),
      o("b", "Hacer una mueca ridícula", "Ser tú mismo", { rel_vestuario: 4, moral: 3, fama: 1 }, "Sacas la lengua. El fotógrafo suspira y dispara. La foto acaba en una pared del vestuario con el título «El Retrato Oficial». El club decide usar la otra, la seria, en el dosier. Pero la tuya tiene más fans."),
      o("c", "Dejar que el fotógrafo te dirija en todo", "Obediencia total", { reputacion: 1, rel_entrenador: 1 }, "Haces exactamente lo que te dice. Te sale una foto perfecta, aburrida y olvidable. El fotógrafo te lo agradece, aunque no sabrá tu nombre en dos semanas."),
    ]),
  S("cv-mascota", "humor", { minAge: 17, clubLevels: ["grande", "europeo"], clubTurns: [2, 400] }, "partido",
    "La mascota se mete en el calentamiento",
    "La mascota del club, un oso gigante de peluche, entra al campo antes del partido y se pone a calentar con vosotros. Nadie sabe por qué. Se tropieza con un cono, rueda cinco metros y se queda inmóvil con las patas al cielo. El estadio estalla en risas. Del interior del traje sale una voz muy seria: «Estoy bien. Seguid».",
    [
      o("a", "Ayudarlo a levantarse con una reverencia", "Un gesto bonito", { rel_aficion: 4, moral: 3, fama: 1 }, "Le das la mano, lo levantas y le haces una reverencia. El estadio lo celebra con una ovación y, después del partido, el chico que lleva el traje te manda una carta de agradecimiento de seis páginas."),
      o("b", "Pasarle un balón y jugar un rondo con él", "Entrar en la gracia", { rel_aficion: 5, moral: 4, rel_vestuario: 2 }, "Le haces un pase corto. El oso intenta devolverlo con la cabeza y el balón rebota en el peluche. Dos minutos de rondo con el oso y la grada pidiendo un gol de la mascota."),
      o("c", "Seguir con tu calentamiento, concentrado", "Profesionalidad", { forma: 1, reputacion: 1 }, "Ni te inmutas. Después del partido, el míster te dice: «Eso es concentración». El oso, desde lejos, te mira con un rencor que tú no tienes forma de ver."),
    ]),
  S("cv-youtuber", "humor", { minAge: 18, maxAge: 30, clubTurns: [2, 400] }, "vestuario",
    "Un compañero se hace youtuber",
    "El extremo suplente ha decidido que lo suyo no es el fútbol, es el contenido. Ha empezado a grabar vídeos en el vestuario, con un trípode, un micro de corbata y la frase «¡Hoy os enseño cómo vive un futbolista!». Te ha puesto en el segundo plano de su vídeo del lunes y tu cara sale en miniatura con una flecha roja.",
    [
      o("a", "Entrar en su vídeo y regalarle un buen momento", "Ser buen compañero", { rel_vestuario: 3, fama: 2, moral: 2 }, "Haces un sketch improvisado donde finges que eres su agente. El vídeo llega al millón de visitas en dos semanas y el extremo te manda una caja de turrón."),
      o("b", "Pedirle que no te grabe: es tu privacidad", "Poner límites", { reputacion: 1, rel_vestuario: -1 }, "Le pides con educación que no te grabe. Lo entiende… hasta que olvida que el trípode sigue en marcha y te capta bailando en la ducha. El vídeo no se sube. Pero existe."),
      o("c", "Chantajearle con una copia del vídeo de la ducha", "Venganza dulce", { rel_vestuario: 4, moral: 3 }, "Le pides cuatro vídeos con tu cara a cambio de no subir el suyo. Él, con lágrimas de risa, acepta. Los dos acabáis en el mismo canal, con cuarenta mil suscriptores nuevos."),
    ]),
  S("cv-cumple-mister", "humor", { minAge: 18, rel: { entrenador: [40, 100] }, clubTurns: [4, 400] }, "vestuario",
    "El cumpleaños del míster",
    "El míster cumple cincuenta años y no lo ha dicho a nadie, pero el utillero lo sabe todo, y esta mañana ha pegado en la pizarra un papel que dice: «Hoy es el cumpleaños de quien manda. Nadie diga nada. Todos, algo». Faltan cinco minutos para que entre. Hay una tarta de supermercado y una vela que nadie sabe de dónde ha salido.",
    [
      o("a", "Organizar una sorpresa con canción", "Con humor y cariño", { rel_entrenador: 5, rel_vestuario: 4, moral: 4 }, "Cuando el míster entra, el vestuario le canta una versión desafinada de «Cumpleaños feliz». Él se queda de pie, rígido, con la cara colorada, y después sonríe con los ojos húmedos. «Sois unos sinvergüenzas», dice."),
      o("b", "Hacer como si nada y felicitarle en privado", "Ser discreto", { rel_entrenador: 3, moral: 2 }, "Al terminar el entrenamiento, le das la mano y le dices «felicidades». Él parpadea, sorprendido: «¿Cómo lo sabías?». «Lo sabe todo el mundo, míster». Apunta algo en su libreta."),
      o("c", "Comprarle un regalo con una dedicatoria divertida", "Un detalle", { patrimonio: -80, rel_entrenador: 4, moral: 3 }, "Le regalas una pizarra pequeña con una frase: «Para que dibujes tus tácticas desde el sofá». Él la cuelga en su despacho y no se la quita en tres temporadas."),
    ]),
  S("cv-subasta", "humor", { minAge: 18, fama: [18, 100], clubTurns: [2, 400] }, "vida",
    "El club subasta tus botas",
    "El club ha montado una subasta benéfica para un hospital infantil y quiere tus botas del último partido. Pero hay un problema: son las únicas que te quedan cómodas y tienes tres partidos seguidos. El director de comunicación te mira con unos ojos que han ensayado delante del espejo: «Es por los niños». Es verdad que es por los niños.",
    [
      o("a", "Donar las botas y comprar unas nuevas esa noche", "Un gesto que cuesta", { patrimonio: -400, rel_aficion: 5, moral: 4, reputacion: 3 }, "Las botas salen por mil doscientos euros. Pasas dos semanas con otras que te hacen ampollas, pero el hospital te manda un dibujo de un niño con tus botas. Lo pones en la taquilla."),
      o("b", "Donar unas botas de entrenamiento firmadas", "Un término medio", { rel_aficion: 3, moral: 2, reputacion: 1 }, "Les das unas botas viejas con tu firma. Se subastan por trescientos euros. Una niña las lleva puestas en el hospital, cuatro tallas más grandes, con la sonrisa más ancha de la sala."),
      o("c", "Ofrecerte a pujar tú mismo por tus botas", "Ironía solidaria", { patrimonio: -900, moral: 3, rel_aficion: 4, reputacion: 2 }, "Pujas por tus propias botas y las pagas tú. El presentador, divertido, lo anuncia al micrófono. La sala se ríe y el hospital recibe el triple de lo esperado. Las botas acaban en una vitrina de tu salón."),
    ]),
  S("cv-siesta", "humor", { minAge: 19, clubTurns: [3, 400] }, "vestuario",
    "La siesta del vestuario",
    "Tras el almuerzo de concentración, hay una tradición sagrada: veinte minutos de siesta antes del entrenamiento. El delantero centro duerme con la boca abierta y el brazo colgando. El portero, de lado, con un antifaz de tela rosa. El capitán, sentado, con los ojos cerrados, finge que medita. Y alguien te ha dado un rotulador negro.",
    [
      o("a", "Dibujarle un bigote al delantero y salir por piernas", "La broma clásica", { rel_vestuario: 4, moral: 4 }, "Le pintas un bigote de mosquetero. Cuando despierta, sale al campo sin saberlo. El míster aguanta tres minutos y luego tiene que girarse. El delantero se entera al ver las fotos. Te jura venganza eterna."),
      o("b", "Dejar el rotulador en la mesa y cerrar los ojos tú también", "Echarte una siesta", { forma: 2, moral: 2 }, "Cierras los ojos. Dormitas diez minutos y despiertas fresco como una rosa. El rotulador, mientras tanto, ha pasado por tres manos distintas y el delantero lleva un bigote, unas patillas y un corazón en la frente."),
      o("c", "Colocar un cartel que ponga: «No molestar. Genios trabajando»", "Un detalle gracioso", { rel_vestuario: 2, moral: 2 }, "Pegas el cartel en la puerta. El míster lo ve, lo lee, lo deja y entra de puntillas para no despertar a nadie. Te lo comenta por la tarde: «Me ha gustado. Es verdad»."),
    ]),
]; 
