/**
 * Sueltas con pocas condiciones: situaciones que le pueden pasar a casi cualquier jugador casi en
 * cualquier momento. Muchas son cómicas o absurdas, algunas conmueven, y varias dejan una marca
 * pequeña que otra escena recoge más adelante. Cuantas más haya, menos se repite la carrera.
 */
import { S, o, r } from "../dsl";
import type { BankScene } from "../types";

export const SUELTAS2: BankScene[] = [
  S("s2x-ascensor", "humor", { minAge: 16, clubTurns: [1, 400], notFlags: ["s2x_ascensor"] }, "vida",
    "Te quedas encerrado en el ascensor del hotel con el míster",
    "Faltan tres horas para el partido y el ascensor del hotel decide que no quiere subir ni bajar. Dentro, estáis tú, el míster y un carrito con cuarenta botellas de agua. Hay una luz de emergencia, un hilo de música de ascensor y un silencio que se puede cortar con un cuchillo. Tras diez minutos, el míster suspira: «Bueno. Hablemos».",
    [
      o("a", "Aprovechar para hablar de fútbol de verdad", "Una charla sincera", { rel_entrenador: 6, moral: 4, flags: { s2x_ascensor: "charla" } }, "Habláis de todo: de tu posición, de lo que él espera, de lo que a ti te cuesta. Cuando abren la puerta, os cuesta salir. «Esto lo repetimos», dice el míster, y no se refiere al ascensor."),
      o("b", "Contarle chistes para no morir de nervios", "Humor de emergencia", { rel_entrenador: 3, moral: 3, flags: { s2x_ascensor: "chistes" } }, "Cuentas tus tres peores chistes. El míster no se ríe con ninguno, pero al cuarto, con una cara de piedra, suelta: «Ése, sí». Sales con una sonrisa y un respeto nuevo."),
      o("c", "Pulsar el botón de alarma con insistencia", "Pánico sano", { moral: -1, rel_entrenador: -1, flags: { s2x_ascensor: "alarma" } }, "El botón suena como una sirena de bomberos. Llegan dos técnicos, el director del hotel y un cámara de prensa. El míster te mira con una paciencia infinita: «Tranquilo, que estás conmigo»."),
    ]),
  S("s2x-fan-regalo", "humor", { minAge: 17, fama: [25, 100], clubTurns: [2, 400], notFlags: ["s2x_regalo"] }, "vida",
    "Un aficionado te regala algo imposible de rechazar",
    "Es un hombre de unos sesenta años, con un abrigo de lana, que te espera a la salida del entrenamiento con una caja de zapatos atada con una cuerda. «Lo hice yo —dice—. No es nada». Dentro hay una maqueta del estadio en palillos, de medio metro, con todas las gradas, los banderines y una figurita que se parece sospechosamente a ti. Tardó, según él, cuatro años.",
    [
      o("a", "Ponerla en el vestuario con una placa de agradecimiento", "Darle un sitio", { rel_aficion: 6, moral: 6, reputacion: 2, flags: { s2x_regalo: "vestuario" } }, "La maqueta se coloca en la entrada del vestuario con una placa: «Hecha con amor por Anselmo». El hombre va a verla cada domingo. A la tercera vez, los jugadores ya le saludan por su nombre."),
      o("b", "Llevártela a casa y cuidarla como un tesoro", "Quedártela", { moral: 5, rel_aficion: 3, flags: { s2x_regalo: "casa" } }, "La pones en el salón, entre tus trofeos. Cada vez que alguien la ve, pregunta. Tú cuentas la historia de Anselmo, y se la sabes de memoria."),
      o("c", "Rechazarla con educación: no tienes dónde ponerla", "Ser práctico", { moral: -3, rel_aficion: -2, flags: { s2x_regalo: "no" } }, "Anselmo asiente, con una dignidad que duele. Se la lleva en brazos, caminando despacio. Una semana después, aparece en la puerta del campo de otro club. Ya no es tuya."),
    ]),
  S("s2x-arbitro", "humor", { minAge: 17, clubTurns: [2, 400], notFlags: ["s2x_arbitro"] }, "partido",
    "El árbitro del domingo es tu antiguo profesor de educación física",
    "Lo reconoces en cuanto sale al campo: el mismo silbato, los mismos calcetines de cuadros y esa manera de mirarte por encima de las gafas. En el sorteo de campos, te sonríe con una mueca de malicia y dice: «Hombre, el vago». Te quedas sin habla. Al final del calentamiento, te llama aparte: «Hoy te voy a pitar todo. Por tu bien».",
    [
      o("a", "Jugar impecable para demostrarle lo que has aprendido", "Dejarle sin palabras", { forma: 2, moral: 5, reputacion: 3, flags: { s2x_arbitro: "impecable" } }, "No cometes ni una falta en noventa minutos. Al final, el árbitro te estrecha la mano: «Podrías haber sido bueno en gimnasia». «Y soy bueno en esto», respondes. Se ríe."),
      o("b", "Hacerle bromas en cada saque de banda", "Divertirte con él", { rel_vestuario: 3, moral: 4, reputacion: -1, flags: { s2x_arbitro: "bromas" } }, "«¡Que no he hecho los abdominales, profe!», le dices. Todos se parten. Te saca una amarilla por «conducta antideportiva con exceso de simpatía». La guardas como recuerdo."),
      o("c", "Pedir al delegado que le cambien", "Evitar el roce", { moral: -2, flags: { s2x_arbitro: "cambio" } }, "El delegado se encoge de hombros: «Es el que toca». Tienes que aguantar noventa minutos con la sombra del colegio. Marcas un gol y le miras de reojo. Él te guiña el ojo."),
    ]),
  S("s2x-vecino", "humor", { minAge: 18, patrimonio: [3000, 100000000], clubTurns: [2, 400], notFlags: ["s2x_vecino"] }, "vida",
    "Tu vecino de abajo se queja de tus pasos",
    "Es un señor mayor, jubilado, con una paciencia que se agota a las diez de la noche. Esta mañana, te deja una nota bajo la puerta: «Camina como un jugador de fútbol. Y lo digo con todo respeto». Es una frase exquisita. No sabes si ríe o te regaña. Llevas semanas descalzo en casa, y aun así, debes de pisar como una manada de elefantes.",
    [
      o("a", "Bajar a pedirle perdón con una botella de vino", "Hacer las paces", { reputacion: 3, moral: 4, patrimonio: -30, flags: { s2x_vecino: "paz" } }, "Llamas a su puerta. Te abre con un delantal de cocina y una sonrisa. «Soy yo quien debería disculparse —dice—. Soy hincha del rival». Os acabáis bebiendo la botella entre fútbol y recuerdos."),
      o("b", "Comprar alfombras para toda la casa", "Solución práctica", { patrimonio: -400, moral: 2, flags: { s2x_vecino: "alfombras" } }, "Tu casa parece una tienda de persas. El vecino, con la nota doblada, te saluda al cruzaros: «Gracias». Cada mañana, un poco menos de ruido y un poco más de paz."),
      o("c", "Ignorar la nota y seguir como siempre", "Pasar", { moral: -1, flags: { s2x_vecino: "paso" } }, "A los dos días, la nota se repite, más corta: «Sigue igual». Al mes, la tercera: «Me mudo». No sabes si es una broma. Esa noche, sigues pisando fuerte."),
    ]),
  S("s2x-llave", "humor", { minAge: 17, clubTurns: [1, 400], notFlags: ["s2x_llave"] }, "vida",
    "Te dejas las llaves de casa dentro y no hay nadie que te abra",
    "Son las doce de la noche, llueve y tu móvil tiene un uno por ciento de batería. Te has quedado fuera, en pijama y con una camiseta del club, frente a tu puerta. Un vecino te mira desde su balcón, con una taza en la mano. En el edificio de enfrente, alguien te ha reconocido y ya ha sacado el móvil. Tu cabeza empieza a calcular los titulares.",
    [
      o("a", "Llamar a un cerrajero de guardia", "Con calma", { patrimonio: -150, moral: 1, flags: { s2x_llave: "cerrajero" } }, "El cerrajero, un hombre con bigote, llega en veinte minutos. Abre la puerta en cuarenta segundos. «Cobro por llegar —dice—, no por abrir». Le firmas una camiseta, y él, con cara de póker, la guarda en el maletín."),
      o("b", "Escalar por el balcón de tu piso", "Aventura", { forma: -1, moral: 3, fama: 2, flags: { s2x_llave: "balcon" } }, "Trepas por una tubería con una elegancia dudosa. Lo consigues. Pero en el último tramo, el pantalón de pijama se engancha y te quedas colgado, en calzoncillos, a tres metros del suelo. El vídeo es viral."),
      o("c", "Llamar a un compañero de confianza para dormir en su casa", "Pedir ayuda", { rel_vestuario: 4, moral: 2, flags: { s2x_llave: "amigo" } }, "Aparece en cinco minutos con una manta y un termo de café. «Hay que ser tonto», dice, riéndose. Te quedas a dormir en su sofá, con su perro acurrucado en los pies."),
    ]),
  S("s2x-bufanda", "humor", { minAge: 16, clubTurns: [2, 400], turn: [4, 8], notFlags: ["s2x_bufanda"] }, "vida",
    "Una abuela te teje una bufanda… del equipo rival",
    "Llega a la puerta del club con un paquete envuelto en papel de periódico. Dentro, una bufanda hecha a mano, de lana gruesa, con rayas rojas y blancas. El problema es que son los colores del equipo rival del barrio. La abuela, que no entiende de fútbol, explica con cariño: «Me dijeron que eran los de aquí». El vestuario, a tu espalda, contiene la respiración.",
    [
      o("a", "Ponértela y agradecérselo con entusiasmo", "Cuestión de gratitud", { rel_aficion: -1, reputacion: 4, moral: 5, flags: { s2x_bufanda: "uso" } }, "Te la pones y posas con ella, con la mejor sonrisa. Los ultras del club, al verlo, te lo perdonan al instante: «Lo ha hecho por una abuela». En el barrio rival, te hacen socio de honor."),
      o("b", "Explicarle con dulzura que son otros colores", "Sinceridad amable", { reputacion: 2, moral: 2, flags: { s2x_bufanda: "explico" } }, "La abuela, avergonzada, vuelve a casa con la bufanda. Al día siguiente, regresa con otra con los colores correctos. Esta vez, tiene tu nombre bordado. Y es la más bonita del mundo."),
      o("c", "Guardarla discretamente y no decir nada", "Evitar la polémica", { moral: 1, flags: { s2x_bufanda: "guardo" } }, "La metes en el fondo de la taquilla. Un día, un compañero la encuentra y lo cuenta a todos. «¡El 9 es un traidor!», gritan, entre carcajadas. Se la regalas al utillero, que es del rival."),
    ]),
  S("s2x-balon-vecino", "humor", { minAge: 17, clubTurns: [1, 400], notFlags: ["s2x_balon"] }, "vida",
    "El balón de unos niños cae en tu jardín y se rompe una ventana",
    "Fue un tiro desviado, de los que se ven venir. El cristal se hace añicos, un jarrón salta por los aires y una vecina grita desde su terraza. En la calle, tres niños de diez años se quedan paralizados: han reconocido tu casa, y saben a quién le han roto la ventana. Uno murmura: «Nos va a matar». Tú abres la puerta con el pijama a medias.",
    [
      o("a", "Salir sonriendo y devolverles el balón firmado", "Convertirlo en un regalo", { rel_aficion: 6, moral: 6, reputacion: 4, patrimonio: -120, flags: { s2x_balon: "firmado" } }, "Les firmas el balón rajado, con la dedicatoria: «Para los que rompen ventanas con estilo». Los niños huyen corriendo, felices. A los pocos días, te dejan una nota de agradecimiento con un dibujo."),
      o("b", "Enfadarte, aunque sea un poco", "Ser el vecino gruñón", { moral: -1, rel_aficion: -2, flags: { s2x_balon: "gruñon" } }, "Les echas una reprimenda de dos minutos. Los niños se van con la cabeza baja. Esa noche, te sientes mal. A la mañana siguiente, hay un balón nuevo en tu puerta con un lazo y una disculpa."),
      o("c", "Invitarlos a jugar un rato en tu jardín", "Jugar con ellos", { moral: 8, rel_aficion: 5, reputacion: 3, flags: { s2x_balon: "jugamos" } }, "Pasas una hora jugando con tres críos que no saben quién eres, pero sí que se te da bien. Al final, te dicen: «Qué bien juegas para ser un viejo». Tienes veintidós años. Te ríes."),
    ]),
  S("s2x-regalo-raro", "humor", { minAge: 17, fama: [25, 100], clubTurns: [2, 400], notFlags: ["s2x_regalo_raro"] }, "vida",
    "Te llega un paquete anónimo con algo muy raro dentro",
    "Es una caja de madera con un lazo. Dentro hay un cojín de cuero, una fotografía en blanco y negro de un portero con bigote y una nota: «No lo abras antes de un partido grande». No hay remitente, ni número, ni firma. El utillero lo huele con desconfianza. El vestuario, intrigado, lo rodea. Alguien sugiere avisar a seguridad.",
    [
      o("a", "Abrirlo con todo el vestuario como espectadores", "Hacerlo un acontecimiento", { rel_vestuario: 5, moral: 4, flags: { s2x_regalo_raro: "abro" } }, "Dentro del cojín hay una moneda antigua con una inscripción: «Para los valientes». El vestuario enmudece. Un veterano, con un hilo de voz, dice: «Es de un amuleto del 82». Nadie sabe qué significa, pero todos quieren tocarlo."),
      o("b", "Entregarlo a seguridad sin abrirlo", "Prudencia", { reputacion: 2, moral: 0, flags: { s2x_regalo_raro: "seguridad" } }, "Seguridad lo examina y confirma que es inocuo. El paquete se archiva en el despacho del club, junto a otros misterios. Durante meses, os preguntaréis qué había dentro."),
      o("c", "Abrirlo en privado y guardarte el secreto", "Misterio personal", { moral: 3, flags: { s2x_regalo_raro: "secreto" } }, "La moneda es antigua. La fotografía, de un portero llamado Casimiro. No tienes ni idea de qué significa, pero te lo llevas a todos los partidos importantes. Funcionar, funciona."),
    ]),
  S("s2x-bautizo", "humor", { minAge: 19, clubTurns: [2, 400], notFlags: ["s2x_bautizo"] }, "vida",
    "Te piden ser padrino en el bautizo del hijo de un compañero",
    "Es la primera vez que te piden algo así. El compañero, nervioso, con el bebé en brazos, te explica: «No tengo a nadie mejor». Hay una iglesia, una madrina muy seria, un sacerdote que odia el fútbol y veinte parientes que quieren un selfie. El bebé, de seis meses, te mira con los ojos muy abiertos. Tienes que sostenerlo, tienes que hablar, tienes que no llorar.",
    [
      o("a", "Aceptar con honor y sostenerlo con cuidado", "Un sí emocionado", { rel_vestuario: 7, moral: 8, reputacion: 3, flags: { s2x_bautizo: "padrino" } }, "Sostienes al bebé con una ternura que no sabías que tenías. En el momento del agua, el niño te agarra el dedo. Se te llenan los ojos. El compañero, a tu lado, te susurra: «Gracias, hermano»."),
      o("b", "Aceptar pero pedir a alguien que haga la parte de hablar", "Con ayuda", { rel_vestuario: 4, moral: 5, flags: { s2x_bautizo: "ayuda" } }, "Tu madre sostiene el pie del bebé mientras tú aguantas la cabeza. El sacerdote, sorprendido, bendice a tres. La foto familiar, con los dos, se hace entrañable."),
      o("c", "Declinar con elegancia y regalar una cuna", "Una excusa amable", { moral: -1, patrimonio: -300, rel_vestuario: 2, flags: { s2x_bautizo: "no" } }, "Tu excusa es una concentración. El compañero asiente, con un gesto triste. La cuna, de roble y con tu apellido grabado, llega al día siguiente. «Mi hijo la usará siempre», dice."),
    ]),
  S("s2x-pelota-calle", "humor", { minAge: 18, fama: [30, 100], clubTurns: [2, 400], notFlags: ["s2x_calle"] }, "vida",
    "Te retan a un partido en la calle contra chavales del barrio",
    "Es un callejón con dos porterías hechas con mochilas, una pared de ladrillo y un público de abuelos en los balcones. Los chavales, de diez a quince años, te miran con hambre: «Si nos ganas, te invitamos a pipas». Tus amigos, a tu lado, murmuran: «Pórtate bien, que están grabando». Tú te quitas el reloj y los pendientes. Hace años que no juegas descalzo.",
    [
      r("a", "Jugar en serio contra ellos, sin regalos", "Competir de verdad", 0.45, "Ganas por 8-7, con un gol de rabona en el último minuto. Los chavales protestan, los abuelos aplauden y tú te llevas una bolsa de pipas. Alguien lo ha grabado y, a las doce de la noche, ya tienes tres millones de visualizaciones.", { fama: 5, rel_aficion: 5, moral: 8, flags: { s2x_calle: "gano" } }, "Pierdes 7-5, con un hat-trick de un crío de doce años llamado Dani. En redes lo llaman «el que hizo temblar al crack». Tu madre te dice: «Menos mal que te ha ganado un niño, así no te pones tonto».", { fama: 3, rel_aficion: 6, moral: 4, flags: { s2x_calle: "pierdo" } }, "forma"),
      o("b", "Dejarles ganar con un teatro bien montado", "Un buen perdedor", { moral: 6, rel_aficion: 5, reputacion: 3, flags: { s2x_calle: "dejo" } }, "Finges lesión, te caes dos veces, y concedes un gol «de otro mundo». Los niños celebran como si hubieran ganado el Mundial. Uno de ellos, al irte, te dice: «Se nota que te dejas». Sonríes."),
    ]),
  S("s2x-sorteo", "humor", { minAge: 16, clubTurns: [2, 400], turn: [4, 6], notFlags: ["s2x_sorteo"] }, "vestuario",
    "El sorteo de Navidad: el vestuario ha comprado un décimo juntos",
    "Es un décimo del 00000, comprado entre todos, con una apuesta de diez euros por cabeza. El utillero lo guarda en una caja fuerte, el portero lo besa cada día, y el capitán ha prohibido hablar del tema. El día del sorteo, a las nueve de la mañana, el vestuario entero está pegado a la radio. Hay veinte corazones latiendo a la vez.",
    [
      r("a", "Aguantar la respiración con el resto", "Esperar el milagro", 0.15, "¡Toca el pedrea! Treinta euros por cabeza, pero la locura es tal que el vestuario celebra con una conga alrededor del utillero. Alguien lo sube a redes con la leyenda: «Nos hemos hecho ricos (de treinta euros)».", { moral: 8, rel_vestuario: 8, patrimonio: 30, flags: { s2x_sorteo: "pedrea" } }, "No toca nada. El utillero rompe el décimo con dignidad y lo tira al cubo. Al salir, el vestuario se dice: «El año que viene, sí». Cada uno se va a su casa con un nudo mínimo y mucha camaradería.", { moral: 1, rel_vestuario: 5, patrimonio: -10, flags: { s2x_sorteo: "nada" } }, "fama"),
      o("b", "Quedarte en la ducha para no oír el resultado", "Esquivar la tensión", { moral: 0, rel_vestuario: -1, flags: { s2x_sorteo: "ducha" } }, "Te escondes en la ducha con los auriculares puestos. Cuando sales, hay un silencio extraño: no ha tocado. Un compañero te mira: «Eres un cobarde». Y tiene razón."),
    ]),
  S("s2x-fiesta-sorpresa", "humor", { minAge: 18, patrimonio: [4000, 100000000], clubTurns: [2, 400], notFlags: ["s2x_fiesta"] }, "vida",
    "Alguien organiza una fiesta en tu casa sin avisarte",
    "Llegas de entrenar y oyes música desde la calle. Subes, abres la puerta y te encuentras treinta personas, un DJ, un barril de cerveza en la cocina y a tu primo, de pie sobre el sofá, con un micrófono. Hay un cartel que dice: «Bienvenido a tu fiesta de bienvenida». Un compañero, sin vergüenza, te pasa un vaso: «Es para que te relajes». Mañana tienes partido.",
    [
      o("a", "Disfrutar un rato y retirarte a una hora prudente", "Con cabeza", { moral: 6, rel_vestuario: 4, reputacion: 2, flags: { s2x_fiesta: "prudente" } }, "Bailas durante una hora, abrazas a todo el mundo y a las once cierras la puerta de tu dormitorio con una sonrisa. A la mañana siguiente, el salón es una zona catastrófica, pero tú juegas fenomenal."),
      o("b", "Dejarte llevar hasta que amanezca", "Fiesta total", { moral: 8, rel_vestuario: 6, forma: -3, rel_entrenador: -3, flags: { s2x_fiesta: "loca" } }, "A las seis de la madrugada, estás cantando en el sofá con la peluca de alguien. Al día siguiente, rindes al cincuenta por ciento. El míster te mira de reojo: «Cuéntame tu noche». Prefieres no hacerlo."),
      o("c", "Echar a todos con educación y quedarte a solas", "Cortar", { forma: 2, moral: -2, rel_vestuario: -2, flags: { s2x_fiesta: "corto" } }, "Les pides que se marchen. Hay quejas y un par de miradas incómodas. Cuando la casa queda en silencio, te quedas pensando si has hecho bien. Mañana, en el vestuario, lo sabrás."),
    ]),
  S("s2x-spoiler", "humor", { minAge: 16, clubTurns: [2, 400], notFlags: ["s2x_spoiler"] }, "vestuario",
    "Un compañero te destripa el final de tu serie favorita",
    "Llevas semanas intentando ver el último capítulo y justo hoy, en el vestuario, a las nueve de la mañana, un compañero grita: «¡Menos mal que mataron al protagonista!». Silencio. Te mira con una sonrisa inocente. «¿Qué? ¿No la habías visto?». Han pasado cuatro segundos y ya tienes los ojos en blanco. Sientes que nada volverá a ser igual.",
    [
      o("a", "Responder con una venganza: destripar la suya", "Ojo por ojo", { rel_vestuario: 3, moral: 3, flags: { s2x_spoiler: "venganza" } }, "Le cuentas cómo termina una novela que sabes que le gusta. El vestuario aplaude. El compañero queda mudo y furioso. A los dos días, se hacen las paces con una cena de pizzas. Los spoilers, por contrato, quedan prohibidos."),
      o("b", "Aceptarlo con resignación y verla igual", "Seguir adelante", { moral: -1, flags: { s2x_spoiler: "resignacion" } }, "La ves de todas formas. Al llegar al final, descubres que el compañero te había mentido: no mataban al protagonista, sino a su perro. Estás a punto de llorar. Es mucho peor."),
      o("c", "Montar un código de silencio para todos los spoilers", "Una norma del vestuario", { rel_vestuario: 5, reputacion: 2, moral: 3, flags: { s2x_spoiler: "norma" } }, "Pegas un cartel en la puerta: «Aquí no se destripan finales». Todos lo respetan, excepto el capitán, que no ve series. Un día, entra y dice «Qué buena el final de Los Serrano». Revolución."),
    ]),
  S("s2x-llamada-equivocada", "humor", { minAge: 16, clubTurns: [1, 400], notFlags: ["s2x_llamada"] }, "vida",
    "Llamas por error al presidente a las tres de la madrugada",
    "Fue un descuido: el contacto de tu mejor amigo está justo encima del contacto del presidente del club. Estabas medio dormido, con el pulgar torpe, y le has dejado un audio de dos minutos, entre risas, hablando de «esa camiseta horrible que ha diseñado el sobrino». El mensaje se ha enviado. No hay marcha atrás. Mañana tienes entrenamiento. Y reunión con la directiva.",
    [
      o("a", "Mandar un mensaje de disculpa inmediato, con humor", "Dar la cara", { reputacion: 3, moral: 2, flags: { s2x_llamada: "disculpa" } }, "Escribes: «Perdón por el audio. La camiseta es preciosa, estaba bromeando». El presidente contesta a las ocho: «Lo mío fue un sobrino, tú tienes buen ojo». Es la mejor respuesta posible."),
      o("b", "Fingir que te han hackeado el móvil", "Mentir con valentía", { moral: -2, reputacion: -2, flags: { s2x_llamada: "hackeo" } }, "El presidente te mira con una ceja levantada. «¿Te han hackeado… y han dicho la verdad?», dice. Te hace repetir la frase, con una sonrisa maliciosa, tres veces. Empiezas a replantearte tu futuro."),
      o("c", "No decir nada y rezar", "Esperar el milagro", { moral: -3, flags: { s2x_llamada: "reza" } }, "A las diez, el presidente te llama a su despacho. Sientes el sudor frío. «Sobre el audio…», empieza. Y de repente, se ríe: «Es verdad que la camiseta es horrenda». La paz regresa a tu vida."),
    ]),
  S("s2x-viejo-amigo", "humor", { minAge: 19, clubTurns: [4, 400], notFlags: ["s2x_viejo_amigo"] }, "vida",
    "Un viejo amigo del colegio aparece en la tele sin avisarte",
    "Estás en el sofá, a punto de ceder al sueño, cuando oyes tu nombre en un programa de televisión: «…y su amigo de la infancia nos cuenta cómo era de pequeño». En la pantalla, un hombre con barba y camisa de cuadros explica entre carcajadas lo de «la cabra que te perseguía en el pueblo». Es Ramón, tu mejor amigo de la escuela. Tu madre, desde otra habitación, grita: «¡Ese es Ramón!».",
    [
      o("a", "Llamarlo en directo para sumarte a la broma", "Entrar al programa", { fama: 4, rel_aficion: 4, moral: 6, flags: { s2x_viejo_amigo: "directo" } }, "Marcas el número del programa. El presentador, sorprendido, te pasa en antena. «La cabra era una oveja», dices. Ramón, con un pañuelo, llora de risa. Os reencontráis tras años sin hablar. Quedáis a cenar al día siguiente."),
      o("b", "Enviarle un mensaje a escondidas y reírte", "Mensaje privado", { moral: 4, flags: { s2x_viejo_amigo: "mensaje" } }, "«Mentiroso. Era una oveja». Ramón responde a los dos minutos: «Era una cabra y tú llorabas». Os pasáis media noche enviándoos recuerdos."),
      o("c", "Apagar la tele y fingir que no te ha pasado", "Pudor", { moral: -1, flags: { s2x_viejo_amigo: "no" } }, "Dejas pasar la ocasión. Meses después, Ramón escribe un libro con tu infancia, y tu nombre sale cuarenta y tres veces. Tienes una sensación rara al leerlo: le has dejado contar tu historia sin ti."),
    ]),
  S("s2x-santo", "humor", { minAge: 16, clubTurns: [2, 400], notFlags: ["s2x_santo"] }, "vida",
    "Una devota te regala una estampita de San Judas para el próximo partido",
    "Es una señora mayor, a la puerta de la iglesia del barrio, con una estampa plastificada y una mirada que no admite negativas. «Para los partidos difíciles —dice—. San Judas Tadeo, patrón de las causas perdidas». Tú no eres creyente, pero tu equipo lleva cinco jornadas sin ganar. Te quedas pensando. La mujer espera, con la mano extendida, a que aceptes.",
    [
      o("a", "Aceptarla y guardarla en tu bota", "Por si acaso", { moral: 4, rel_aficion: 2, flags: { s2x_santo: "bota" } }, "Esa tarde ganáis 3-0 y marcas un doblete. El vestuario descubre la estampita y se hace una procesión. Pasa de taquilla en taquilla, y acaba con un bigote dibujado y una corbata."),
      o("b", "Agradecérsela pero declinar con respeto", "Sin ofender", { reputacion: 2, moral: 1, flags: { s2x_santo: "no" } }, "La señora lo acepta con una sonrisa. «Pues por ti rezaré yo», dice. Esa noche, ganáis 2-1. En la bota, no hay estampa. Pero sabes que alguien, en una capilla, ha encendido una vela."),
    ]),
  S("s2x-regalo-hermana", "humor", { minAge: 17, clubTurns: [2, 400], notFlags: ["s2x_hermana"] }, "vida",
    "Tu hermana pequeña te pide el favor más difícil del mundo",
    "Es una cena de familia como cualquier otra, hasta que, sin avisar, tu hermana suelta: «Necesito que vengas a mi función de teatro del cole». Se hace un silencio. La función es el sábado, a las cinco. Tienes partido a las seis y dos horas de viaje. Ella te mira con unos ojos que no admiten excusas. Tu madre, desde la cocina, tose.",
    [
      o("a", "Ir a la función y llegar tarde al partido", "Arriesgar por ella", { moral: 9, rel_entrenador: -4, reputacion: 3, flags: { s2x_hermana: "voy" } }, "Entras en el teatro de puntillas, con la camiseta del club bajo el abrigo. Ves a tu hermana hacer de árbol durante diez minutos con una dignidad enorme. Llegas al partido en el minuto 25. El míster te mira: «Más vale que sea por algo»."),
      o("b", "Explicárselo y prometerle una cena especial", "Una alternativa", { moral: 2, patrimonio: -100, flags: { s2x_hermana: "cena" } }, "Tu hermana se cruza de brazos. «Vale —dice—, pero la próxima vez, tú eres el árbol». Os reís. Esa noche, en una pizzería, os contáis cómo ha ido el día, y ella, en voz baja, te perdona."),
      o("c", "Grabarle un vídeo animándola desde el hotel", "Un gesto a distancia", { moral: 3, flags: { s2x_hermana: "video" } }, "El vídeo, de un minuto, con una canción de ánimo, llega a tu hermana justo antes de salir al escenario. Lo lee en el móvil de tu madre. Le dedica la actuación. Y al acabar, te dice: «Lo hice por ti»."),
    ]),
  S("s2x-balon-oro-casa", "humor", { minAge: 18, fama: [35, 100], clubTurns: [3, 400], notFlags: ["s2x_balon_oro"] }, "vida",
    "Un amigo te regala un «Balón de Oro» de plástico para tu salón",
    "Es del tamaño de una bola de bolos, brillante, con una base de plástico dorado y una placa: «Al mejor jugador de la historia, según su madre». Tu amigo, con una sonrisa de orgullo, lo coloca en el centro de tu salón. Tu pareja o tu madre lo miran con una ceja levantada. «Está genial —dices—. Pero no lo puedo mover». Es pesadísimo.",
    [
      o("a", "Dejarlo ahí con orgullo", "Convertirlo en tu trofeo oficial", { moral: 5, reputacion: -1, flags: { s2x_balon_oro: "salon" } }, "Cada visita que llega pregunta: «¿Es de verdad?». «Es el único que me llevaré», contestas. A los años, cuando ganes uno de verdad, lo pondrás junto al falso. Y habrá quien prefiera el de plástico."),
      o("b", "Esconderlo en el trastero antes de que alguien lo vea", "Pudor", { moral: 1, flags: { s2x_balon_oro: "trastero" } }, "Lo arrastras al trastero. A los tres meses, tu pareja lo saca para una fiesta de disfraces. Sale en una foto con la leyenda: «El Balón de Oro más barato de la historia»."),
      o("c", "Pintarle encima tu apellido con un rotulador", "Personalizarlo", { moral: 4, rel_vestuario: 2, flags: { s2x_balon_oro: "firmado" } }, "Escribes tu apellido con una letra enorme. El balón gana, curiosamente, cierto valor sentimental. Un compañero te lo pide para un sorteo benéfico. Y recauda doscientos euros."),
    ]),
];
