/**
 * Traspasos y mercado: rumores con sal y pimienta, cenas con directivos,
 * despedidas, y todo lo que pasa cuando de verdad llegas a un club nuevo. Las
 * escenas de rumores usan la bandera especial "@interest" para que un club
 * muestre interés de verdad y, tras ello, pueda llegar una oferta formal.
 */
import { S, o, r, th, after } from "../dsl";
import type { BankScene } from "../types";

export const TRASPASOS: BankScene[] = [
  S("tr-camarero", "traspaso", { market: "abierta", fama: [22, 100], minAge: 18 }, "prensa",
    "Un camarero «lo sabe todo»",
    "Pides un café en el bar de siempre y el camarero, sin mirarte, suelta mientras limpia la barra: «Yo no he dicho nada, pero me ha dicho un primo que trabaja en un hotel de Madrid que ayer comieron allí unos señores con corbata, preguntando por ti». Se hace un silencio dramático. Detrás, la cafetera pita como si quisiera añadir algo.",
    [
      o("a", "Dejarte querer: «Yo escucho lo que haga falta»", "Alimentar el rumor", { fama: 2, moral: 2, rel_aficion: -2, flags: { "@interest": "prensa" } }, "Sueltas una media sonrisa y el camarero lo cuenta en la cola del pan. A la mañana siguiente, un tertuliano lo dice en la radio con voz de misterio. Tu móvil empieza a sonar."),
      o("b", "Quitarle hierro: «Esto es un rumor de bar»", "Mantener la calma", { reputacion: 1, rel_aficion: 2 }, "Pagas el café, dejas dos euros de propina y sales con una sonrisa neutra. El camarero se queda mirando el cuadro con cara de «con esta gente no hay forma»."),
      o("c", "Llamar a tu agente al momento", "Dejar que lo gestione", { rel_representante: 2, moral: 1 }, "Tu representante contesta con la boca llena: «¿Quién te lo ha dicho?». «El camarero». Silencio. «Qué bueno es el camarero», murmura, y cuelga para hacer tres llamadas."),
    ]),
  S("tr-foto-aeropuerto", "traspaso", { market: "abierta", fama: [30, 100], minAge: 18 }, "prensa",
    "Una foto tuya en el aeropuerto que no eres tú",
    "Circula por redes una foto de un tipo con tu misma estatura, tu misma gorra y una maleta de turista, entrando en un aeropuerto. El pie de foto dice: «ÚLTIMA HORA: {el_interes} ya tiene al fichaje bomba». No eres tú. Te lo juras. Pero los comentarios son tan convencidos que, por un segundo, hasta tú dudas.",
    [
      o("a", "Subir una foto desde casa con el pijama y el pie «Aeropuerto de mi salón»", "Responder con humor", { fama: 3, rel_aficion: 3, moral: 3 }, "La foto de tu sofá se hace más viral que el bulo. La gente te escribe «el más fiel del mundo» y el club comparte tu foto con un guiño. Dos horas después, el tipo del aeropuerto pide disculpas."),
      o("b", "No decir nada: el silencio también habla", "Dejar correr el bulo", { fama: 2, rel_aficion: -3, flags: { "@interest": "prensa" } }, "No desmientes nada. Durante tres días, los comentaristas hablan del «silencio sospechoso». Un club, de verdad, se pone en contacto con tu agente."),
      o("c", "Mandar una nota oficial desmintiendo el rumor", "Zanjarlo con formalidad", { rel_aficion: 3, reputacion: 2, rel_entrenador: 1 }, "Tu nota de cinco líneas desinfla el bulo en una hora. El míster la lee en voz alta a tus compañeros: «Esto es un profesional», y alguien responde «es un aburrido»."),
    ], { weight: 1.2 }),
  S("tr-agente-cena", "traspaso", { flags: ["transfer_interest"], market: "abierta", minAge: 18 }, "representante",
    "Una cena con alguien del club que te quiere",
    "Tu representante te ha reservado mesa en un restaurante con manteles de tela y un camarero que susurra. Allí te espera un directivo de {el_interes}, con traje de tres piezas y una libreta donde ya ha apuntado cifras. «Solo vamos a charlar», dice tu agente, que nunca ha charlado en su vida. El primer plato llega con una carta de vinos que cuesta más que tus botas.",
    [
      o("a", "Escuchar con interés y sin comprometerte", "Mantener la puerta abierta", { rel_representante: 3, fama: 1, moral: 2 }, "Escuchas dos horas de promesas y de proyectos. Sales con el estómago lleno y la cabeza en dos sitios. Tu agente, en el coche: «Perfecto. Ya saben que existes»."),
      o("b", "Dejar claro que tu prioridad es tu club", "Ser fiel", { rel_aficion: 4, rel_entrenador: 2, rel_representante: -2, reputacion: 2 }, "Le dices al directivo, con educación, que tu cabeza está en tu club. Él asiente muy serio y apunta algo. Tu agente se pone una servilleta en la cara."),
      o("c", "Pedir condiciones muy exigentes a ver qué pasa", "Subir la apuesta", { rel_representante: 2, fama: 2, moral: 3 }, "Pides un contrato desproporcionado. El directivo traga saliva, mira a tu agente y dice «vamos a estudiarlo». Tu agente te mira como si hubieras cantado la Traviata."),
    ]),
  S("tr-despedida-adelantada", "traspaso", { market: "abierta", fama: [25, 100], minAge: 18, clubTurns: [3, 400], rel: { vestuario: [35, 100] } }, "vestuario",
    "Tus compañeros te despiden por adelantado",
    "Con los rumores de fichaje, el vestuario ha empezado a tratarte con una mezcla de cariño y burla. El lateral te lleva el bolso. El delantero te pide el número de tu futuro entrenador. Alguien ha pegado en tu taquilla una hoja que dice: «PLAZA LIBRE (próximamente)». El capitán se acerca con cara de funeral fingida: «Si te vas, que sea a un club que nos pague bien las visitas».",
    [
      o("a", "Seguirles el juego y repartir 'recuerdos' del club", "Entrar en la broma", { rel_vestuario: 5, moral: 4 }, "Le regalas al lateral una bufanda, al delantero un llavero y al capitán una foto tuya enmarcada con la frase «El que se va deja huella». Todos te abrazan entre carcajadas."),
      o("b", "Cortar los rumores con seriedad", "Que quede claro", { rel_vestuario: -2, reputacion: 2, rel_entrenador: 1 }, "Les dices que no te vas, que son rumores. Se hace un silencio incómodo. «Qué serio», murmura el lateral. Pero al día siguiente todos te tratan con más cuidado."),
      o("c", "Contestar que sí, que te vas, pero a la selección del barrio", "Una réplica", { rel_vestuario: 4, moral: 3, fama: 1 }, "Dices que fichas por el equipo de los jubilados del parque de enfrente. Tres veteranos del club, que pasaban por allí, aplauden. Te regalan un dominó."),
    ]),
  S("tr-mister-mira", "traspaso", { market: "abierta", roles: ["titular", "rotacion"], fama: [28, 100], minAge: 18 }, "entrenamiento",
    "El míster te mira distinto desde que suenas",
    "No es que el míster te trate peor: es que te mira con la cabeza ladeada, como quien examina un cuadro caro que tal vez vaya a perder. Hoy te ha cambiado de posición en un rondo por primera vez en meses y no ha dado explicación. En la ducha, el segundo entrenador te comenta con una naturalidad sospechosa: «Aquí tienes casa, ¿eh?».",
    [
      o("a", "Pedirle al míster que te hable claro", "Dar la cara", { rel_entrenador: 3, moral: 2, reputacion: 1 }, "Le pides cinco minutos. El míster se cruza de brazos y te cuenta que «los rumores le complican la plantilla». Te agradece la franqueza con un apretón de manos y una exigencia nueva."),
      o("b", "Rendir al máximo y que hablen los números", "Callar y entrenar", { forma: 2, media: 1, rel_entrenador: 2 }, "Entrenas con una intensidad de la que ni tú te creías capaz. El míster te mira con una media sonrisa y apunta algo. Al final de la semana vuelves a tu posición en el rondo."),
      o("c", "Dejar que la sospecha crezca: tú tampoco hablas", "Tensión silenciosa", { moral: -2, rel_entrenador: -3 }, "Ni tú dices nada ni él. La tensión se corta con cuchillo y en el vestuario lo notan. El jueves, el utillero te pregunta en voz baja si «todo bien en casa»."),
    ]),
  S("tr-ultras-pancarta", "traspaso", { flags: ["transfer_interest"], minAge: 18, fama: [30, 100], rel: { aficion: [50, 100] } }, "vida",
    "Una pancarta en la grada: «Tu sitio es éste»",
    "Los de la grada de animación han desplegado una pancarta enorme antes del partido: «CRACKS COMO TÚ, DE AQUÍ NO SE VAN». Debajo, en letras más pequeñas, alguien ha escrito «(y si se van, que paguen)». Lo han preparado con cariño, con rotuladores, con sábanas de abuela y con la presencia de tres críos con cara de apurados.",
    [
      o("a", "Saludar a la grada con las dos manos en el escudo", "Un gesto con peso", { rel_aficion: 8, moral: 5, fama: 2 }, "Levantas las manos al escudo. La grada ruge. En el palco, el presidente se levanta con una sonrisa. En una oficina de otra ciudad, un directivo cierra una carpeta con un suspiro."),
      o("b", "Mirar hacia otro lado y concentrarte", "No comprometerte", { forma: 1, rel_aficion: -2, reputacion: 1 }, "Haces como si no vieras nada. La grada lo nota. En el descanso, un comentarista dice «el crack está ya con la cabeza en otro sitio». No es verdad. Pero lo parece."),
      o("c", "Responder en redes tras el partido: «La vais a tener siempre»", "Una frase con peso", { rel_aficion: 6, moral: 4, fama: 3, rel_representante: -2 }, "Escribes cuatro palabras que se hacen eco de la pancarta. En tu agencia, tu agente lee el mensaje y deja caer el móvil en la taza de café."),
    ]),
  S("tr-consejo-compañero", "traspaso", { minAge: 19, clubTurns: [4, 400], rel: { vestuario: [45, 100] } }, "vestuario",
    "Un compañero te pregunta si debería irse",
    "El central de veintisiete años te espera en el parking con las llaves del coche en la mano y una cara que no es suya. Le ha llegado una oferta de un club que le pagaría el doble pero donde no sabe si jugaría. «Tú has estado en esa situación», te dice. «¿Qué haces cuando tienes que elegir entre el dinero, los minutos y el cariño?».",
    [
      o("a", "Decirle que siga su corazón, sea lo que sea", "Aconsejar con calidez", { rel_vestuario: 4, moral: 3 }, "Le cuentas con calma lo que tú harías y le dices que decida con la cabeza fría. El central te abraza sin avisar. Semanas después te llama para contarte lo que ha elegido.", { thread: th("favor", "el central", "Te pidió consejo antes de decidir su futuro y te lo agradeció") }),
      o("b", "Decirle que se vaya: el dinero no espera", "Consejo pragmático", { rel_vestuario: 1, reputacion: -1 }, "Le dices lo que piensas: que el fútbol es corto y que hay que aprovecharlo. El central asiente despacio y se va. En el vestuario, alguien murmura que «el crack ya piensa como un mercenario»."),
      o("c", "Decirle que no te metes en esas cosas", "Mantenerte al margen", { rel_vestuario: -2, moral: -1 }, "Le dices que cada uno decide lo suyo. Se aleja decepcionado. A los dos días, en el entrenamiento, no te pasa un balón. A la semana, sí."),
    ]),
  S("tr-presi-comida", "traspaso", { minAge: 20, fama: [30, 100], media: [68, 99], clubTurns: [10, 400] }, "representante",
    "El presidente te invita a comer",
    "Llega un sobre con el escudo del club a tu casa y una tarjeta escrita a mano: «Comida de trabajo, 14:00, sin agentes. Quiero hablar contigo de ti». Cuando llegas, el presidente te espera en un reservado con dos platos de croquetas y una expresión de padre que va a dar una noticia que no sabe cómo dar. Se levanta a abrazarte antes de saludarte.",
    [
      o("a", "Escuchar su propuesta de renovación con calma", "Dejarle hablar", { rel_entrenador: 1, rel_representante: -1, patrimonio: 1200, moral: 3, fama: 1 }, "Te ofrece una subida generosa y una cláusula alta. Le dices que lo hablarás con tu agente. El presidente asiente, orgulloso, y pide postre. Te vas con la cartera más ancha."),
      o("b", "Pedirle un proyecto deportivo que te convenza", "Pedir ambición", { rel_aficion: 2, reputacion: 3, moral: 2 }, "Le dices que no se trata de dinero, sino de ganar cosas. El presidente se queda callado un instante y luego sonríe: «Tienes razón. Dame tiempo»."),
      o("c", "Salirte por la tangente con una broma", "No comprometerte", { rel_representante: 1, moral: 1 }, "Haces una broma con las croquetas y cambias de tema tres veces. El presidente te mira con una paciencia admirable: «Eres peor que mi hijo, y mi hijo es político»."),
    ]),
  S("tr-primera-mañana", "traspaso", { flags: ["clubs_history"], clubTurns: [1, 3], minAge: 17 }, "vestuario",
    "Tu primera mañana en {club}",
    "Llegas al centro de entrenamiento con el estómago en un puño y una bolsa de deporte nueva. Hay un vestuario que huele a otro champú y a otra historia. Alguien te ha dejado una taquilla en una esquina, justo al lado de la puerta del baño. Veinte pares de ojos te miran de reojo. El capitán se acerca con la mano ya extendida.",
    [
      o("a", "Saludar a todos uno por uno por su nombre", "Entrar con educación", { rel_vestuario: 5, moral: 3, reputacion: 2 }, "Te has aprendido los nombres en el coche, con la lista que te mandó el club. Cuando saludas a cada uno por su nombre, el vestuario se sorprende. El capitán te da una palmada: «Aquí vas a estar bien»."),
      o("b", "Hablar con el míster antes que con nadie", "Ir al jefe", { rel_entrenador: 4, rel_vestuario: -1 }, "Entras directo al despacho y te presentas. El míster te mira con una sonrisa contenida: «Ya veremos»."),
      o("c", "Meter algún chiste para romper el hielo", "Humor desde el minuto uno", { rel_vestuario: 4, moral: 4, fama: 1 }, "Dices que has fichado por «la taquilla del baño, que es lo más importante». El lateral se ríe tanto que se cae del banco. Ya eres uno más."),
    ], { weight: 1.5 }),
  S("tr-dorsal", "traspaso", { flags: ["clubs_history"], clubTurns: [1, 4], minAge: 17 }, "vestuario",
    "Tu dorsal de siempre ya tiene dueño",
    "Siempre has llevado el mismo número. Es tu amuleto, tu historia y la camiseta que sale en la foto de tu madre. Pero en {club} lo lleva un veterano al que adoran en la grada. El utillero te lo explica con mucha pena: «Tienes el 27, el 31 y el 34. El tuyo, lo siento, está ocupado». Hay una pausa dramática. Y, entonces, el veterano entra al vestuario.",
    [
      o("a", "Quedarte con otro número sin hacer ruido", "Aceptar la tradición", { rel_vestuario: 4, rel_aficion: 2, reputacion: 2 }, "Eliges el 27 con una sonrisa. El veterano lo ve y asiente con respeto. Meses después, cuando se retire, te cederá su dorsal con una ceremonia que te hará llorar."),
      o("b", "Pedirle el número al veterano con respeto", "Una conversación a solas", { moral: 2, rel_vestuario: -1 }, "Hablas con él a solas. Te escucha y dice que no. No se enfada. Tú tampoco. Pero algo se queda flotando entre los dos."),
      o("c", "Ofrecer un trato: una cena a cambio del número", "Comprar el dorsal", { patrimonio: -300, rel_vestuario: 2, moral: 3 }, "Le ofreces una cena de las buenas. El veterano acepta tras pensarlo un minuto largo. Sales con tu número y con un amigo, aunque se queda con un ojo en la cuenta."),
    ]),
  S("tr-rueda-presentacion", "traspaso", { flags: ["clubs_history"], clubTurns: [1, 2], minAge: 18, fama: [18, 100] }, "prensa",
    "Tu primera rueda de prensa en {club}",
    "El presidente te presenta con una frase larguísima sobre el proyecto, la ilusión y «una nueva etapa». La sala de prensa tiene cuarenta periodistas, dos cámaras de televisión y un chico que graba con el móvil. El primer micrófono se te acerca con una pregunta con trampa: «¿Es cierto que querías jugar en otro sitio?».",
    [
      o("a", "Decir que siempre soñaste con esta camiseta", "Un clásico que funciona", { rel_aficion: 5, fama: 2, moral: 3 }, "Dices la frase con voz firme. La grada, que lo sigue por la radio, se ilusiona. Un periodista veterano arquea una ceja, pero nadie lo discute."),
      o("b", "Hablar con sinceridad: otro club también te quería", "Sin mentiras", { rel_aficion: -2, reputacion: 3, fama: 3 }, "Reconoces que valoraste otras opciones. Los periodistas lo apuntan como si fuera una confesión. Algunos aficionados lo llaman «honestidad» y otros «descaro»."),
      o("c", "Desviar con humor: «Yo juego donde me pidan»", "Evitar el mal trago", { rel_aficion: 1, moral: 2 }, "Tu frase queda un poco vacía, pero la sala ríe. El presidente, a tu lado, se frota las manos con una alegría un poco exagerada."),
    ]),
  S("tr-silbidos-primer-fallo", "traspaso", { flags: ["clubs_history"], clubTurns: [2, 6], roles: ["titular", "rotacion"], minAge: 18 }, "partido",
    "La afición te silba al primer error",
    "Fallas un control sencillo y desde el fondo cae un silbido corto, largo, quirúrgico. No es un abucheo: es un recordatorio. «Aquí no regalamos nada». Lo oyes con toda claridad, con ese eco que parece aumentar. Esta tarde, en esta ciudad, aún eres un desconocido que ha costado dinero.",
    [
      o("a", "Responder con una jugada de calidad en el siguiente balón", "Ganártelo en el campo", { forma: 2, rel_aficion: 4, moral: 3 }, "Pides el balón y te inventas un regate que deja sentado al defensa. La grada pasa de silbar a gritar. Al final del partido, un aficionado te grita: «¡Ahora sí!»."),
      o("b", "Aplaudir a la grada con ironía", "Lanzar un guante", { rel_aficion: -3, fama: 2, moral: 2 }, "Aplaudes con una media sonrisa. La grada, ofendida, responde con un silbido más largo. Tardarás semanas en ganarte el cariño que has estropeado."),
      o("c", "Ignorarlo: eres un profesional", "Cabeza fría", { moral: 1, reputacion: 1 }, "Haces como que no has oído nada. Pero esa noche, en la cama, repites el silbido en tu cabeza. Y decides que el próximo balón será el mejor de tu vida."),
    ]),
  S("tr-piso-nuevo", "traspaso", { flags: ["clubs_history"], clubTurns: [1, 5], minAge: 18, patrimonio: [3000, 100000000] }, "vida",
    "Buscar piso en la nueva ciudad",
    "El club te ha dado una lista de tres inmobiliarias de confianza y una advertencia de la secretaria: «No firmes nada sin ver el segundo piso». El primer piso tiene una vista maravillosa y un vecino que hace ejercicios de trompeta. El segundo, una cocina que parece un baño. El tercero, una terraza y un gato que parece formar parte de la comunidad.",
    [
      o("a", "Quedarte con el piso del gato", "Elegir con el corazón", { moral: 6, patrimonio: -400, rel_vestuario: 1 }, "Te instalas con el gato, que se llama Perico, y vive en la terraza con aire de dueño. En una semana, ya duerme encima de tu camiseta de entrenamiento."),
      o("b", "Elegir el piso con vistas y esperar a que se vaya el trompetista", "Optimismo", { moral: 2, patrimonio: -500 }, "El trompetista ensaya a las siete de la mañana. A la tercera semana, ya sabes sus tres canciones. A la cuarta, le pagas un café y te prometen que habrá un concierto privado."),
      o("c", "Pedirle al club que te encuentre algo mejor", "Delegar", { rel_entrenador: 1, moral: 1 }, "El club te mete en un hotel de cuatro estrellas mientras busca. Ya llevas tres semanas viviendo en una habitación con vistas a una rotonda. Te sientes un turista rico."),
    ]),
  S("tr-taxista", "traspaso", { flags: ["clubs_history"], clubTurns: [1, 8], minAge: 17, fama: [15, 100] }, "vida",
    "El taxista que lo sabe todo de tu club nuevo",
    "Subes a un taxi en la nueva ciudad y el conductor te mira por el retrovisor con una sonrisa cómplice: «¿Tú eres el nuevo?». Durante veinte minutos te cuenta la historia del club, las manías del presidente, lo que opina del míster y por qué el portero «está gafado». Te pide un autógrafo en una libreta de recibos y te cobra de más con total naturalidad.",
    [
      o("a", "Quedarte a charlar una hora en el coche aparcado", "Aprender del experto", { rel_aficion: 3, moral: 4, fama: 1 }, "El taxista te presenta a su hermano, a su cuñado y a su suegra por videollamada. Al final, sabes más del club que el presidente. Tres días después, te llega un obsequio con tu nombre."),
      o("b", "Dejarle una propina enorme y entrar en el hotel", "Ser generoso", { patrimonio: -80, rel_aficion: 2, moral: 2 }, "Le dejas un billete de cincuenta. El taxista se queda mirando el billete como si fuera un trofeo. En el barrio se corre la voz: «El nuevo es buen tío»."),
      o("c", "Decirle que no hablas con desconocidos", "Distancia educada", { moral: -1, reputacion: 1 }, "El taxista se queda en silencio y te lleva al hotel con una expresión de dolor teatral. Esa noche, en la radio local, dicen que «el nuevo es muy reservado»."),
    ]),
  S("tr-exclub-mensaje", "traspaso", { flags: ["clubs_history"], clubTurns: [4, 40], minAge: 19 }, "vida",
    "Un mensaje de tu antiguo vestuario",
    "El grupo de WhatsApp de tu antiguo club ha vuelto a la vida: han puesto una foto de la taquilla que dejaste, con tu nombre aún en la etiqueta, y un mensaje del utillero: «Sigue siendo tuya. Nadie se atreve a abrirla». Debajo, veinte comentarios de compañeros que te echan de menos. Y un vídeo del lateral cantándote una canción inventada.",
    [
      o("a", "Contestar con un vídeo cantando de vuelta", "Agradecer con humor", { moral: 6, rel_vestuario: 2 }, "Grabas un vídeo con voz desafinada y lo mandas. En {el_ex_club} lo ven en el vestuario, entre risas. Al día siguiente, el utillero te manda una foto de la taquilla con una vela encendida."),
      o("b", "Escribir un agradecimiento sincero a cada uno", "Cuidar los vínculos", { moral: 5, reputacion: 2 }, "Pasas toda la tarde escribiendo mensajes a mano. Algunos tardan días en contestar, y uno de ellos, el más duro, solo escribe: «Gracias por acordarte»."),
      o("c", "Dejar el mensaje en visto, con culpa", "Pasar página", { moral: -2 }, "Lo lees dos veces y lo dejas. No sabes qué decir. Esa noche, en la cama, se te hace un nudo del que no hablas con nadie."),
    ]),
  S("tr-mercado-cierre", "traspaso", { market: "enero", turn: [8, 9], fama: [25, 100], minAge: 18 }, "representante",
    "El último día del mercado",
    "A las diez de la mañana, tu agente te llama con una voz de película de acción: «Esto se mueve. No salgas de casa. Ni apagues el móvil. Ni te duches». A las tres, te envía un audio con ruido de fondo de aeropuerto. A las seis, un mensaje de una sola palabra: «Espera». A las once de la noche, cuando ya te has dormido en el sofá, suena otra vez.",
    [
      o("a", "Mantenerte despierto con café hasta que cierre el mercado", "Vivir el drama", { moral: -1, rel_representante: 3, flags: { "@interest": "agente" } }, "Pasas la noche en vela mirando el móvil. Al final, no se concreta nada, pero sí queda una oferta sobre la mesa para el verano. Tu agente, cansado, te escribe: «Esto no ha terminado»."),
      o("b", "Apagar el móvil y dormir: lo que sea será", "Desconectar", { moral: 3, rel_representante: -3, forma: 1 }, "Apagas el móvil y te duermes como un niño. Al despertar tienes cuarenta y siete llamadas perdidas y un mensaje de tu agente: «No me vuelvas a hacer esto». No pasó nada. Pero no lo sabes."),
      o("c", "Decirle a tu agente que cierre cualquier operación sin más", "Dejarlo en sus manos", { rel_representante: 4, moral: 1 }, "Le das carta blanca. Tu agente se queda en silencio una eternidad. «Confías demasiado», murmura, emocionado. No cierra nada sin consultarte, y eso te hace confiar más."),
    ]),
  S("tr-padre-opinion", "traspaso", { flags: ["transfer_interest"], minAge: 17, maxAge: 28 }, "vida",
    "Tu padre opina de tu futuro",
    "Tu padre te llama una noche, lo cual es raro, porque siempre llama a tu madre y esta se pasa el teléfono. Va directo: «Me han dicho en el bar que te quiere {el_interes}. Yo no entiendo mucho, pero me parece que deberías pensar en tu madre antes de irte tan lejos». Lo dice con voz de quien lleva ensayando la frase tres días.",
    [
      o("a", "Escucharle con paciencia y prometerle que lo pensarás", "Respetar su opinión", { moral: 4, rel_representante: -1 }, "Le prometes que lo pensarás. Tu padre, aliviado, te cuenta que ha comprado un abono para viajar si te vas. «Por si acaso», dice. Y se te humedecen los ojos con una frase tan práctica."),
      o("b", "Decirle que es tu carrera y que decidirás tú", "Marcar límites", { moral: -2, reputacion: 1 }, "Le dices que lo entiendes pero que decides tú. Hay un silencio largo al otro lado. «Claro, hijo», dice por fin. Cuelga con una voz que no es la suya."),
      o("c", "Invitarlo a ver el proyecto del club contigo", "Hacerle partícipe", { moral: 5, rel_representante: 1, patrimonio: -300 }, "Le pagas un viaje a ver las instalaciones. Tu padre se pasa dos horas preguntando por el césped y el sistema de riego. Vuelve convencido de que «es un club serio, con buena hierba»."),
    ]),
  S("tr-trasferible", "traspaso", { roles: ["suplente", "apartado"], minAge: 20, clubTurns: [8, 400], media: [45, 78] }, "representante",
    "Te ponen en la lista de transferibles",
    "Te enteras por un compañero que lo vio en una hoja de la oficina: tu nombre, entre diez más, bajo un título frío: «Posibles salidas». No te lo ha dicho nadie. Ni el míster, ni el director deportivo, ni tu agente. Ahora entiendes por qué el utillero te mira con ternura y el masajista te ha dado dos veces el mismo masaje.",
    [
      o("a", "Pedir una reunión con el director deportivo", "Dar la cara", { rel_entrenador: 1, moral: 2, reputacion: 2 }, "El director deportivo te recibe con dos cafés y una explicación honesta: «Hay que hacer sitio. No es nada personal». Te ofrece buscar un destino bueno antes de que acabe el mercado."),
      o("b", "Llamar a tu agente y que mueva el mercado", "Buscar salida ya", { rel_representante: 3, moral: 1, flags: { "@interest": "agente" } }, "Tu agente, que ya lo sabía, finge sorpresa con muchísima solvencia. «Ya estaba en ello», dice, y te manda una lista de tres clubes con cara de despedida."),
      o("c", "Ponerte a entrenar con más rabia que nunca", "Demostrar que se equivocan", { forma: 3, rel_entrenador: 2, moral: -1 }, "Entrenas como si te fuera la vida. El míster lo nota y te retira del listado en una reunión que nadie te cuenta. A cambio, la tensión con el director deportivo no se va."),
    ]),
  S("tr-carta-aficion", "traspaso", { flags: ["transfer_interest"], minAge: 18, rel: { aficion: [55, 100] } }, "vida",
    "Una carta de una niña de la grada",
    "En el buzón del club hay un sobre azul con dibujos de balones y corazones. Es de una niña de nueve años que se llama Lucía. Escribe con letra grande y faltas de ortografía tiernas: «No te vayas, porque mi papá ya me ha dicho que si te vas ya no vamos al estadio. Y yo quiero ir contigo. Te quiero mucho». Hay un dibujo de ti, con una corona.",
    [
      o("a", "Contestarle con una carta escrita a mano", "Un gesto que cuesta tiempo", { rel_aficion: 6, moral: 6, reputacion: 2 }, "Le escribes una carta de una página, con tu mejor letra. Su padre te manda una foto de la niña con ella, enmarcada, en su habitación."),
      o("b", "Mandarle una camiseta firmada y un vídeo", "Algo rápido y bonito", { rel_aficion: 4, moral: 3 }, "Grabas un mensaje corto y mandas una camiseta. La niña la lleva a todas partes y en el colegio dice que «el crack es su amigo»."),
      o("c", "Guardar la carta en un cajón y no contestar", "Evitar el compromiso", { moral: -3 }, "La guardas junto a tus llaves. Cada vez que abres el cajón, aparece el dibujo con la corona. A los dos meses, ya no puedes mirarla sin que se te encoja el pecho."),
    ]),
  S("tr-periodista-cifra", "traspaso", { market: "abierta", minAge: 18, fama: [25, 100] }, "prensa",
    "Un periodista inventa tu cifra",
    "Un portal de rumores publica con letras enormes: «El crack cobrará 14 millones por temporada. Su agente ya ha elegido casa en Londres». Ni lo uno ni lo otro. Tu hermana te manda captura con diez interrobantes. Tu agente te llama a la segunda: «Esto sale de un sitio concreto, y no soy yo». El periodista, a los pocos minutos, te manda un mensaje: «Perdona si te he molestado».",
    [
      o("a", "Desmentirlo con un mensaje fino y sin hostilidad", "Cortar el bulo con clase", { reputacion: 3, rel_aficion: 2, fama: 1 }, "Publicas un mensaje con una frase educada: «Ni cifra ni casa». El periodista, avergonzado, se disculpa en directo. El bulo se desinfla en media hora."),
      o("b", "Callar y dejar que el bulo siga", "Sacar partido", { fama: 3, rel_aficion: -2, flags: { "@interest": "prensa" } }, "No dices nada. El bulo crece y, tres días después, alguien de verdad llama a tu agente preguntando «por esos catorce millones». Tu agente pone cara de póker."),
      o("c", "Responder con ironía sobre la casa de Londres", "Un chiste", { fama: 3, rel_aficion: 3, moral: 3 }, "Subes una foto de tu casa de siempre con la frase «Mi casa de Londres». Medio país se ríe contigo, y el periodista, por cortesía, rectifica sin que se lo pidas."),
    ]),
  S("tr-hincha-bufanda", "traspaso", { flags: ["transfer_interest"], minAge: 19, rel: { aficion: [48, 100] }, fama: [30, 100] }, "vida",
    "Un hincha te regala su bufanda de 1987",
    "A la salida del entrenamiento, un señor mayor con gorra de visera te para con las dos manos. Lleva una bufanda desteñida, con el escudo de otra época. «Es de 1987. La llevaba el día que ganamos la Copa. La he guardado treinta años y quiero que la lleves tú hasta que te retires. Aquí. Con nosotros». No pide nada. No quiere foto. Solo que la cojas.",
    [
      o("a", "Aceptarla con respeto y prometerle quedarte", "Un compromiso con la grada", { rel_aficion: 9, moral: 6, rel_representante: -2, reputacion: 3 }, "La coges con las dos manos. Le prometes algo que no sabes si podrás cumplir. El señor se limpia una lágrima y se va sin decir adiós.", { thread: th("promesa", "el señor de la bufanda", "Le prometiste llevar su bufanda de 1987 hasta que te retires") }),
      o("b", "Aceptarla, pero sin hacer ninguna promesa", "Gratitud sin compromiso", { rel_aficion: 4, moral: 3 }, "La aceptas, le das las gracias con el corazón en la mano, y no prometes nada. El señor lo entiende. «Con eso me basta», dice."),
      o("c", "Rechazarla con educación: no puedes aceptarlo", "Evitar la presión", { rel_aficion: -3, moral: -2 }, "Le dices que es demasiado. El señor guarda la bufanda sin una palabra. Su silencio se te queda dentro durante meses."),
    ], { isMilestone: true, milestoneType: "escena", imageScene: "Photorealistic photo of an elderly football fan handing a faded vintage club scarf to a young footballer outside a training ground, warm afternoon light, emotional and understated documentary style" }),
  S("tr-presidente-ex", "traspaso", { flags: ["clubs_history"], clubTurns: [10, 400], minAge: 21 }, "prensa",
    "Tu antiguo presidente habla de ti",
    "En una entrevista de radio, el presidente de {el_ex_club} dice: «Aquel chico fue una pena, se fue por dinero, pero le deseamos lo mejor». Lo han recogido todas las cuentas de noticias. Tu agente te manda el enlace con tres emojis de llamas. Por supuesto, ese presidente nunca te dijo lo que ahora dice en voz alta.",
    [
      o("a", "Responder con elegancia: «Siempre agradecido»", "Pasar página con clase", { reputacion: 4, rel_aficion: 2, moral: 2 }, "Subes un mensaje de agradecimiento a tu antiguo club. El presidente lo ve y, a la mañana siguiente, rectifica en otra entrevista. Hay cosas que se arreglan sin gritar."),
      o("b", "Responder con una frase afilada", "Defender tu versión", { fama: 3, rel_aficion: 1, reputacion: -2 }, "Escribes cuatro líneas con segundas y las compartes. Los aficionados del club nuevo aplauden; los del antiguo te silbarán durante años."),
      o("c", "No responder: los hechos hablan solos", "Dejar que pase", { moral: 1, reputacion: 1 }, "Lees la entrevista tres veces. Cierras el móvil. En el entrenamiento, el míster te dice «yo no lo habría hecho mejor». Y te das cuenta de que hablaba de otra cosa."),
    ]),
  S("tr-compañero-vuelve", "traspaso", { flags: ["clubs_history"], clubTurns: [12, 400], minAge: 21 }, "vestuario",
    "Un excompañero ficha por tu club",
    "Entra por la puerta del vestuario con una bolsa en cada mano y la sonrisa de siempre. Es el lateral que compartió contigo dos años de cantera, tres cenas de Navidad y un robo de coche que aún no saben cómo ocurrió. Te ve y suelta un grito: «¡Eh, tú!». Se abre un paréntesis de risas y empujones. El resto de la plantilla os mira como si hubieran llegado dos primos del pueblo.",
    [
      o("a", "Ayudarle a instalarse y presentarle al grupo", "Ser su anfitrión", { rel_vestuario: 5, moral: 6 }, "Le enseñas el club, los cafés, los bares donde se come bien y el sitio donde esconder el coche de las multas. En una semana, el lateral ya tiene su banda de amigos."),
      o("b", "Mantener un poco de distancia: ya no sois críos", "Profesionalidad", { reputacion: 1, rel_vestuario: 1, moral: -1 }, "Os saludáis con afecto, pero cada uno va a lo suyo. Él lo nota. Al segundo mes, os sentáis juntos en un bar y se disuelve el hielo."),
      o("c", "Hacerle la novatada de bienvenida que te hicieron a ti", "Una venganza cariñosa", { rel_vestuario: 6, moral: 5 }, "Le escondes la maleta en el techo del autobús. El lateral la busca durante veinte minutos y la encuentra con un lazo. «Esto no se olvida», dice. Y no se olvida."),
    ]),
  S("tr-oferta-rival", "traspaso", { flags: ["transfer_interest"], minAge: 19, fama: [35, 100], clubTurns: [6, 400] }, "prensa",
    "El rival de toda la vida te quiere",
    "Es de esos rumores que mueven calles enteras. El eterno rival de tu club ha preguntado por ti. No es una consulta cualquiera: es el enemigo íntimo, el que te hace ganar o perder el orgullo. Tu madre te llama llorando. Tu padre te manda un mensaje con una sola palabra: «No». Y en el grupo del barrio, Nacho ha escrito: «Como firmes, te quito del grupo».",
    [
      o("a", "Negarte en rotundo públicamente", "Cerrar la puerta de golpe", { rel_aficion: 8, moral: 4, reputacion: 2, rel_representante: -3 }, "Escribes en un comunicado que jamás jugarías con ellos. El estadio, el domingo, te dedica una ovación de pie. Tu agente, resignado, borra tres llamadas de su móvil."),
      o("b", "No cerrar la puerta: escuchar es gratis", "Mantener las opciones", { moral: 1, rel_aficion: -5, rel_representante: 3, flags: { "@interest": "agente" } }, "Dices que escuchas a todos. La grada lo toma como una traición y te silban en el siguiente partido. Tu agente sonríe: acaba de subir tu caché."),
      o("c", "Responder con humor: «Solo si me regalan la sede»", "Salir con una broma", { fama: 3, rel_aficion: 3, moral: 3 }, "Tu frase se hace viral en cinco minutos. Los dos clubes la comparten. El rival te manda una camiseta con tu nombre y la frase estampada, y tu club otra con la respuesta."),
    ]),
  S("tr-cola-agencia", "traspaso", { market: "abierta", minAge: 18, fama: [20, 100] }, "representante",
    "Tres agentes quieren representarte",
    "En una semana, tres agentes distintos han intentado hablar contigo. Uno por Instagram, con corazones. Uno por teléfono, con un tono aterciopelado. Y uno en persona, en la puerta del gimnasio, con un maletín y un perfume de vestíbulo de hotel. Todos prometen lo mismo: «Yo te llevo a un grande». El tuyo de siempre, mientras tanto, no se entera. O sí.",
    [
      o("a", "Contárselo a tu agente de siempre", "Lealtad", { rel_representante: 5, reputacion: 3, moral: 2 }, "Tu agente escucha en silencio. «Gracias por decírmelo», dice, y por primera vez en meses te invita a cenar. Esa noche, te descubre que lleva tiempo preparándote algo grande."),
      o("b", "Quedar con uno de ellos por curiosidad", "Explorar", { rel_representante: -4, moral: 2, flags: { "@interest": "agente" } }, "Cenas con el del perfume. Te habla de contratos con cifras imposibles. Tu agente lo sabe antes del postre: alguien se lo ha dicho. La confianza queda un poco agrietada."),
      o("c", "Cortar a todos con un mensaje seco", "Zanjar el asunto", { reputacion: 2, rel_representante: 2, moral: 1 }, "Escribes el mismo mensaje a los tres. Los tres contestan con educación y uno con un meme de despedida. Esa semana, tu móvil descansa."),
    ]),
]; 
