/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanteraRouteImport } from './routes/cantera'
import { Route as CarreraRouteImport } from './routes/carrera'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as LegadoRouteImport } from './routes/legado'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as RelacionesRouteImport } from './routes/relaciones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteraRoute = CanteraRouteImport.update({
  id: '/cantera',
  path: '/cantera',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreraRoute = CarreraRouteImport.update({
  id: '/carrera',
  path: '/carrera',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const LegadoRoute = LegadoRouteImport.update({
  id: '/legado',
  path: '/legado',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const RelacionesRoute = RelacionesRouteImport.update({
  id: '/relaciones',
  path: '/relaciones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cantera': typeof CanteraRoute
  '/carrera': typeof CarreraRoute
  '/historia': typeof HistoriaRoute
  '/legado': typeof LegadoRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/relaciones': typeof RelacionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cantera': typeof CanteraRoute
  '/carrera': typeof CarreraRoute
  '/historia': typeof HistoriaRoute
  '/legado': typeof LegadoRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/relaciones': typeof RelacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cantera': typeof CanteraRoute
  '/carrera': typeof CarreraRoute
  '/historia': typeof HistoriaRoute
  '/legado': typeof LegadoRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/relaciones': typeof RelacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cantera'
    | '/carrera'
    | '/historia'
    | '/legado'
    | '/onboarding'
    | '/patrimonio'
    | '/relaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cantera'
    | '/carrera'
    | '/historia'
    | '/legado'
    | '/onboarding'
    | '/patrimonio'
    | '/relaciones'
  id:
    | '__root__'
    | '/'
    | '/cantera'
    | '/carrera'
    | '/historia'
    | '/legado'
    | '/onboarding'
    | '/patrimonio'
    | '/relaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanteraRoute: typeof CanteraRoute
  CarreraRoute: typeof CarreraRoute
  HistoriaRoute: typeof HistoriaRoute
  LegadoRoute: typeof LegadoRoute
  OnboardingRoute: typeof OnboardingRoute
  PatrimonioRoute: typeof PatrimonioRoute
  RelacionesRoute: typeof RelacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantera': {
      id: '/cantera'
      path: '/cantera'
      fullPath: '/cantera'
      preLoaderRoute: typeof CanteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrera': {
      id: '/carrera'
      path: '/carrera'
      fullPath: '/carrera'
      preLoaderRoute: typeof CarreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legado': {
      id: '/legado'
      path: '/legado'
      fullPath: '/legado'
      preLoaderRoute: typeof LegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relaciones': {
      id: '/relaciones'
      path: '/relaciones'
      fullPath: '/relaciones'
      preLoaderRoute: typeof RelacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanteraRoute: CanteraRoute,
  CarreraRoute: CarreraRoute,
  HistoriaRoute: HistoriaRoute,
  LegadoRoute: LegadoRoute,
  OnboardingRoute: OnboardingRoute,
  PatrimonioRoute: PatrimonioRoute,
  RelacionesRoute: RelacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
